//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.WMS.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.WMS.Data.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abortion is not supported for mission type &apos;{0}&apos;..
        /// </summary>
        public static string AbortionIsNotSupportedForMissionType {
            get {
                return ResourceManager.GetString("AbortionIsNotSupportedForMissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual picked quantity ({0}) cannot be greater than the remaining quantity to dispatch ({1})..
        /// </summary>
        public static string ActualPickedQuantityCannotBeGreaterThanTheRemainingQuantityToDispatch {
            get {
                return ResourceManager.GetString("ActualPickedQuantityCannotBeGreaterThanTheRemainingQuantityToDispatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create a pick mission from a request that does not specify the target bay..
        /// </summary>
        public static string CannotCreatePickMissionFromRequestThatDoesNotSpecifyTargetBay {
            get {
                return ResourceManager.GetString("CannotCreatePickMissionFromRequestThatDoesNotSpecifyTargetBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process scheduler request id={0}..
        /// </summary>
        public static string CannotProcessSchedulerRequest {
            get {
                return ResourceManager.GetString("CannotProcessSchedulerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment position and size must be specified..
        /// </summary>
        public static string CompartmentPositionAndSizeMustBeSpecified {
            get {
                return ResourceManager.GetString("CompartmentPositionAndSizeMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified set of compartments cannot be inserted in the loading unit..
        /// </summary>
        public static string CompartmentSetCannotBeInsertedInLoadingUnit {
            get {
                return ResourceManager.GetString("CompartmentSetCannotBeInsertedInLoadingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment size is not specified..
        /// </summary>
        public static string CompartmentSizeIsNotSpecified {
            get {
                return ResourceManager.GetString("CompartmentSizeIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock cannot be zero when the item pairing is not fixed..
        /// </summary>
        public static string CompartmentStockCannotBeZeroWhenItemPairingIsNotFixed {
            get {
                return ResourceManager.GetString("CompartmentStockCannotBeZeroWhenItemPairingIsNotFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item stock in the compartment cannot be greater that compartment&apos;s maximum capacity..
        /// </summary>
        public static string CompartmentStockGreaterThanMaxCapacity {
            get {
                return ResourceManager.GetString("CompartmentStockGreaterThanMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment&apos;s X position is not specified..
        /// </summary>
        public static string CompartmentXPositionIsNotSpecified {
            get {
                return ResourceManager.GetString("CompartmentXPositionIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment&apos;s Y position is not specified..
        /// </summary>
        public static string CompartmentYPositionIsNotSpecified {
            get {
                return ResourceManager.GetString("CompartmentYPositionIsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion is not supported for mission type &apos;{0}&apos;..
        /// </summary>
        public static string CompletionIsNotSupportedForMissionType {
            get {
                return ResourceManager.GetString("CompletionIsNotSupportedForMissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get content type for file &apos;{0}&apos;..
        /// </summary>
        public static string CouldNotGetContentTypeForFile {
            get {
                return ResourceManager.GetString("CouldNotGetContentTypeForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compartment with the same features already exists..
        /// </summary>
        public static string DuplicateCompartmentType {
            get {
                return ResourceManager.GetString("DuplicateCompartmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item request has missing mandatory fields..
        /// </summary>
        public static string ItemRequestHasMissingMandatoryFields {
            get {
                return ResourceManager.GetString("ItemRequestHasMissingMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading unit request has missing mandatory fields..
        /// </summary>
        public static string LoadingUnitRequestHasMissingMandatoryFields {
            get {
                return ResourceManager.GetString("LoadingUnitRequestHasMissingMandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New max capacity {0} must be equal or greater than current max capacity {1}..
        /// </summary>
        public static string NewMaxCapacityMustBeEqualOrGreaterThanCurrent {
            get {
                return ResourceManager.GetString("NewMaxCapacityMustBeEqualOrGreaterThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bay with the id {0} exists..
        /// </summary>
        public static string NoBayWithTheIdExists {
            get {
                return ResourceManager.GetString("NoBayWithTheIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity with the specified id={0} exists..
        /// </summary>
        public static string NoEntityExists {
            get {
                return ResourceManager.GetString("NoEntityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mission with id &apos;{0}&apos; exists..
        /// </summary>
        public static string NoMissionWithIdExists {
            get {
                return ResourceManager.GetString("NoMissionWithIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough available compartments to serve the request..
        /// </summary>
        public static string NotEnoughAvailableCompartmentsToServeTheRequest {
            get {
                return ResourceManager.GetString("NotEnoughAvailableCompartmentsToServeTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only loading unit withdrawal operations are allowed..
        /// </summary>
        public static string OnlyLoadingUnitWithdrawalOperationsAreAllowed {
            get {
                return ResourceManager.GetString("OnlyLoadingUnitWithdrawalOperationsAreAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only pick and put requests are supported..
        /// </summary>
        public static string OnlyPickAndPutRequestsAreSupported {
            get {
                return ResourceManager.GetString("OnlyPickAndPutRequestsAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick missions cannot be created for scheduler operation type &apos;{0}&apos;..
        /// </summary>
        public static string PickMissionsCannotBeCreatedForSchedulerOperationType {
            get {
                return ResourceManager.GetString("PickMissionsCannotBeCreatedForSchedulerOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; does not exist on entity &apos;{1}&apos;..
        /// </summary>
        public static string PropertyDoesNotExistOnEntity {
            get {
                return ResourceManager.GetString("PropertyDoesNotExistOnEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put missions cannot be created for scheduler operation type &apos;{0}&apos;..
        /// </summary>
        public static string PutMissionsCannotBeCreatedForSchedulerOperationType {
            get {
                return ResourceManager.GetString("PutMissionsCannotBeCreatedForSchedulerOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be equal to 1 if Registration Number is specified..
        /// </summary>
        public static string QuantityMustBeOneIfRegistrationNumber {
            get {
                return ResourceManager.GetString("QuantityMustBeOneIfRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested quantity must be positive..
        /// </summary>
        public static string RequestedQuantityMustBePositive {
            get {
                return ResourceManager.GetString("RequestedQuantityMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string TheListTypeIsNotSupported {
            get {
                return ResourceManager.GetString("TheListTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method argument {0} should not be null..
        /// </summary>
        public static string TheMethodArgumentShouldNotBeNull {
            get {
                return ResourceManager.GetString("TheMethodArgumentShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified item does not exist..
        /// </summary>
        public static string TheSpecifiedItemDoesNotExist {
            get {
                return ResourceManager.GetString("TheSpecifiedItemDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property &apos;{0}&apos; is not found..
        /// </summary>
        public static string TheSpecifiedPropertyIsNotFound {
            get {
                return ResourceManager.GetString("TheSpecifiedPropertyIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified scheduler request type is not supported..
        /// </summary>
        public static string TheSpecifiedSchedulerRequestTypeIsNotSupported {
            get {
                return ResourceManager.GetString("TheSpecifiedSchedulerRequestTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; for field &apos;{1}&apos; is already used by another entry..
        /// </summary>
        public static string TheValueForFieldIsAlreadyUsedByAnotherEntry {
            get {
                return ResourceManager.GetString("TheValueForFieldIsAlreadyUsedByAnotherEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Registration Number is already present for this Item..
        /// </summary>
        public static string ThisRegistrationNumberIsAlreadyPresentForThisItem {
            get {
                return ResourceManager.GetString("ThisRegistrationNumberIsAlreadyPresentForThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the specified mission because it has no associated loading unit..
        /// </summary>
        public static string UnableToCompleteTheSpecifiedMissionBecauseItHasNoAssociatedLoadingUnit {
            get {
                return ResourceManager.GetString("UnableToCompleteTheSpecifiedMissionBecauseItHasNoAssociatedLoadingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the specified mission. Actual put quantity ({0}) cannot be negative or zero..
        /// </summary>
        public static string UnableToCompleteTheSpecifiedMissionBecauseOfActualPutQuantity {
            get {
                return ResourceManager.GetString("UnableToCompleteTheSpecifiedMissionBecauseOfActualPutQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the specified mission. The associated compartment could not be retrieved..
        /// </summary>
        public static string UnableToCompleteTheSpecifiedMissionBecauseOfAssociatedCompartmentNotRetrieved {
            get {
                return ResourceManager.GetString("UnableToCompleteTheSpecifiedMissionBecauseOfAssociatedCompartmentNotRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to complete the specified mission. The associated loading unit could not be retrieved..
        /// </summary>
        public static string UnableToCompleteTheSpecifiedMissionBecauseOfAssociatedLoadingUnitNotRetrieved {
            get {
                return ResourceManager.GetString("UnableToCompleteTheSpecifiedMissionBecauseOfAssociatedLoadingUnitNotRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the row because no row with id={0} exists..
        /// </summary>
        public static string UnableToExecuteTheListRowBecauseNoRowExists {
            get {
                return ResourceManager.GetString("UnableToExecuteTheListRowBecauseNoRowExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the list row (id={0}). The rows of type &apos;{1}&apos; are not supported..
        /// </summary>
        public static string UnableToExecuteTheListRowBecauseOfTypeNotSupported {
            get {
                return ResourceManager.GetString("UnableToExecuteTheListRowBecauseOfTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute the list row (id={0}). {1}..
        /// </summary>
        public static string UnableToExecuteTheListRowWithDescription {
            get {
                return ResourceManager.GetString("UnableToExecuteTheListRowWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to interpret enumeration value for &apos;{0}&apos;..
        /// </summary>
        public static string UnableToInterpretEnumerationValueFor {
            get {
                return ResourceManager.GetString("UnableToInterpretEnumerationValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to suspend the row because no row with id={0} exists..
        /// </summary>
        public static string UnableToSuspendTheListRowBecauseNoRowExists {
            get {
                return ResourceManager.GetString("UnableToSuspendTheListRowBecauseNoRowExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{0}&apos; must be positive..
        /// </summary>
        public static string ValueOfMustBePositive {
            get {
                return ResourceManager.GetString("ValueOfMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of &apos;{0}&apos; must be strictly positive..
        /// </summary>
        public static string ValueOfMustBeStrictlyPositive {
            get {
                return ResourceManager.GetString("ValueOfMustBeStrictlyPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; represents an invalid quantity. Dispatched mission quantity cannot be negative or zero..
        /// </summary>
        public static string ValueRepresentsAnInvalidQuantity {
            get {
                return ResourceManager.GetString("ValueRepresentsAnInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When registration number is specified, the requested quantity must be 1..
        /// </summary>
        public static string WhenRegistrationNumberIsSpecifiedTheRequestedQuantityMustBeOne {
            get {
                return ResourceManager.GetString("WhenRegistrationNumberIsSpecifiedTheRequestedQuantityMustBeOne", resourceCulture);
            }
        }
    }
}
