// <auto-generated />
using System;
using Ferretto.VW.MAS_DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferretto.VW.MAS_DataLayer.Migrations
{
    [DbContext(typeof(DataLayerContext))]
    [Migration("20190717093118_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Coord");

                    b.Property<int>("LoadingUnitId");

                    b.Property<int>("Priority");

                    b.Property<long>("Side");

                    b.Property<long>("Status");

                    b.Property<long>("WorkingStatus");

                    b.HasKey("CellId");

                    b.HasIndex("LoadingUnitId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.ConfigurationValue", b =>
                {
                    b.Property<long>("CategoryName");

                    b.Property<long>("VarName");

                    b.Property<long>("VarType");

                    b.Property<string>("VarValue");

                    b.HasKey("CategoryName", "VarName");

                    b.ToTable("ConfigurationValues");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.Error", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Issue");

                    b.Property<string>("Reason");

                    b.HasKey("Code");

                    b.ToTable("Errors");

                    b.HasData(
                        new { Code = 1001, Description = "Errore database", Issue = 5 },
                        new { Code = 1002, Description = "Errore caricamento configurazione", Issue = 5 },
                        new { Code = 1003, Description = "Errore inizializzazione dati", Issue = 5 },
                        new { Code = 1004, Description = "Errore salvataggio dati", Issue = 5 },
                        new { Code = 1005, Description = "Errore rientro cassetto", Issue = 5 },
                        new { Code = 1006, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1007, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1008, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1009, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1010, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1011, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1012, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1013, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1014, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1015, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1016, Description = "Errore rientro baia", Issue = 5 },
                        new { Code = 1017, Description = "Errore posizionamento", Issue = 5 }
                    );
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.ErrorStatistic", b =>
                {
                    b.Property<int>("Code");

                    b.Property<int>("TotalErrors");

                    b.HasKey("Code");

                    b.ToTable("ErrorStatistics");

                    b.HasData(
                        new { Code = 1001, TotalErrors = 11 },
                        new { Code = 1002, TotalErrors = 7 },
                        new { Code = 1003, TotalErrors = 5 },
                        new { Code = 1004, TotalErrors = 3 },
                        new { Code = 1005, TotalErrors = 2 },
                        new { Code = 1006, TotalErrors = 1 },
                        new { Code = 1007, TotalErrors = 1 },
                        new { Code = 1008, TotalErrors = 1 },
                        new { Code = 1009, TotalErrors = 1 },
                        new { Code = 1010, TotalErrors = 1 },
                        new { Code = 1011, TotalErrors = 1 },
                        new { Code = 1012, TotalErrors = 1 },
                        new { Code = 1013, TotalErrors = 1 },
                        new { Code = 1014, TotalErrors = 1 },
                        new { Code = 1015, TotalErrors = 1 },
                        new { Code = 1016, TotalErrors = 0 }
                    );
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.FreeBlock", b =>
                {
                    b.Property<int>("FreeBlockId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlockSize");

                    b.Property<int>("BookedCellsNumber");

                    b.Property<decimal>("Coord");

                    b.Property<int>("LoadingUnitId");

                    b.Property<int>("Priority");

                    b.Property<long>("Side");

                    b.Property<int>("StartCell");

                    b.HasKey("FreeBlockId");

                    b.HasIndex("LoadingUnitId");

                    b.ToTable("FreeBlocks");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.LoadingUnit", b =>
                {
                    b.Property<int>("LoadingUnitId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CellPosition");

                    b.Property<string>("Description");

                    b.Property<decimal>("Height");

                    b.Property<decimal>("MaxWeight");

                    b.Property<long>("Status");

                    b.Property<decimal>("Weight");

                    b.HasKey("LoadingUnitId");

                    b.ToTable("LoadingUnits");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.LogEntry", b =>
                {
                    b.Property<int>("LogEntryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<string>("Description");

                    b.Property<string>("Destination");

                    b.Property<string>("ErrorLevel");

                    b.Property<string>("Exception");

                    b.Property<string>("Level");

                    b.Property<string>("LoggerName");

                    b.Property<string>("Message");

                    b.Property<string>("Source");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Type");

                    b.HasKey("LogEntryID");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.RuntimeValue", b =>
                {
                    b.Property<long>("CategoryName");

                    b.Property<long>("VarName");

                    b.Property<long>("VarType");

                    b.Property<string>("VarValue");

                    b.HasKey("CategoryName", "VarName");

                    b.ToTable("RuntimeValues");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.Cell", b =>
                {
                    b.HasOne("Ferretto.VW.MAS_DataLayer.LoadingUnit", "LoadingUnit")
                        .WithMany("Cells")
                        .HasForeignKey("LoadingUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.ErrorStatistic", b =>
                {
                    b.HasOne("Ferretto.VW.MAS_DataLayer.Error", "Error")
                        .WithMany("CodeErrorStatistics")
                        .HasForeignKey("Code");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.FreeBlock", b =>
                {
                    b.HasOne("Ferretto.VW.MAS_DataLayer.LoadingUnit", "LoadingUnit")
                        .WithMany("FreeBlocks")
                        .HasForeignKey("LoadingUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
