// <auto-generated />
using Ferretto.VW.MAS_DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferretto.VW.MAS_DataLayer.Migrations
{
    [DbContext(typeof(DataLayerContext))]
    partial class DataLayerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Coord");

                    b.Property<int>("Priority");

                    b.Property<long>("Side");

                    b.Property<long>("Status");

                    b.HasKey("CellId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.ConfigurationValue", b =>
                {
                    b.Property<long>("VarName");

                    b.Property<long>("VarType");

                    b.Property<string>("VarValue");

                    b.HasKey("VarName");

                    b.ToTable("ConfigurationValues");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.FreeBlock", b =>
                {
                    b.Property<int>("FreeBlockId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlockSize");

                    b.Property<int>("BookedCellsNumber");

                    b.Property<decimal>("Coord");

                    b.Property<int>("Priority");

                    b.Property<long>("Side");

                    b.Property<int>("StartCell");

                    b.HasKey("FreeBlockId");

                    b.ToTable("FreeBlocks");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.RuntimeValue", b =>
                {
                    b.Property<long>("VarName");

                    b.Property<long>("VarType");

                    b.Property<string>("VarValue");

                    b.HasKey("VarName");

                    b.ToTable("RuntimeValues");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.StatusLog", b =>
                {
                    b.Property<int>("StatusLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LogMessage");

                    b.HasKey("StatusLogId");

                    b.ToTable("StatusLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
