// <auto-generated />
using System;
using Ferretto.VW.MAS_DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferretto.VW.MAS_DataLayer.Migrations
{
    [DbContext(typeof(DataLayerContext))]
    partial class DataLayerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Coord");

                    b.Property<int>("LoadingUnitId");

                    b.Property<int>("Priority");

                    b.Property<long>("Side");

                    b.Property<long>("Status");

                    b.Property<long>("WorkingStatus");

                    b.HasKey("CellId");

                    b.HasIndex("LoadingUnitId");

                    b.ToTable("Cells");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.ConfigurationValue", b =>
                {
                    b.Property<long>("VarName");

                    b.Property<long>("VarType");

                    b.Property<string>("VarValue");

                    b.HasKey("VarName");

                    b.ToTable("ConfigurationValues");

                    b.HasData(
                        new { VarName = 9L, VarType = 3L, VarValue = "169.254.231.248" },
                        new { VarName = 10L, VarType = 0L, VarValue = "17221" },
                        new { VarName = 11L, VarType = 3L, VarValue = "169.254.231.10" },
                        new { VarName = 12L, VarType = 0L, VarValue = "502" }
                    );
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.FreeBlock", b =>
                {
                    b.Property<int>("FreeBlockId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlockSize");

                    b.Property<int>("BookedCellsNumber");

                    b.Property<decimal>("Coord");

                    b.Property<int>("LoadingUnitId");

                    b.Property<int>("Priority");

                    b.Property<long>("Side");

                    b.Property<int>("StartCell");

                    b.HasKey("FreeBlockId");

                    b.HasIndex("LoadingUnitId");

                    b.ToTable("FreeBlocks");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.GeneralInfo", b =>
                {
                    b.Property<int>("GeneralInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool>("Alfa_Num_Bay1");

                    b.Property<bool>("Alfa_Num_Bay2");

                    b.Property<bool>("Alfa_Num_Bay3");

                    b.Property<int>("Bays_Quantity");

                    b.Property<string>("City");

                    b.Property<string>("Client_Code");

                    b.Property<string>("Client_Name");

                    b.Property<string>("Country");

                    b.Property<double>("Height");

                    b.Property<double>("Height_Bay1");

                    b.Property<double>("Height_Bay2");

                    b.Property<double>("Height_Bay3");

                    b.Property<double>("Height_From_Machine_Bottom_Bay1");

                    b.Property<double>("Height_From_Machine_Bottom_Bay2");

                    b.Property<double>("Height_From_Machine_Bottom_Bay3");

                    b.Property<DateTime>("Installation_Date");

                    b.Property<bool>("Laser_Bay1");

                    b.Property<bool>("Laser_Bay2");

                    b.Property<bool>("Laser_Bay3");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<int>("Machine_Number_In_Area");

                    b.Property<string>("Model");

                    b.Property<string>("Order");

                    b.Property<string>("Province");

                    b.Property<string>("Serial");

                    b.Property<int>("Shutter_Type_Bay1");

                    b.Property<int>("Shutter_Type_Bay2");

                    b.Property<int>("Shutter_Type_Bay3");

                    b.Property<int>("Type_Bay1");

                    b.Property<int>("Type_Bay2");

                    b.Property<int>("Type_Bay3");

                    b.Property<bool>("WMS_On");

                    b.HasKey("GeneralInfoId");

                    b.ToTable("GeneralInfos");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.LoadingUnit", b =>
                {
                    b.Property<int>("LoadingUnitId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CellPosition");

                    b.Property<decimal>("Height");

                    b.Property<long>("Status");

                    b.Property<decimal>("Weight");

                    b.HasKey("LoadingUnitId");

                    b.ToTable("LoadingUnits");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.RuntimeValue", b =>
                {
                    b.Property<long>("VarName");

                    b.Property<long>("VarType");

                    b.Property<string>("VarValue");

                    b.HasKey("VarName");

                    b.ToTable("RuntimeValues");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.StatusLog", b =>
                {
                    b.Property<int>("StatusLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LogMessage");

                    b.HasKey("StatusLogId");

                    b.ToTable("StatusLogs");
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.Cell", b =>
                {
                    b.HasOne("Ferretto.VW.MAS_DataLayer.LoadingUnit", "LoadingUnit")
                        .WithMany("Cells")
                        .HasForeignKey("LoadingUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ferretto.VW.MAS_DataLayer.FreeBlock", b =>
                {
                    b.HasOne("Ferretto.VW.MAS_DataLayer.LoadingUnit", "LoadingUnit")
                        .WithMany("FreeBlocks")
                        .HasForeignKey("LoadingUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
