-- Areas / Aisles
SET IDENTITY_INSERT Areas ON;
INSERT INTO Areas (Id, Name) VALUES (1, 'Area Traslo');
SET IDENTITY_INSERT Areas OFF;

SET IDENTITY_INSERT Aisles ON;
INSERT INTO Aisles (Id, Name, AreaId, Floors, Columns) VALUES (1, 'Corridoio 1', 1, 5, 10);
INSERT INTO Aisles (Id, Name, AreaId, Floors, Columns) VALUES (2, 'Corridoio 2', 1, 5, 10);
INSERT INTO Aisles (Id, Name, AreaId, Floors, Columns) VALUES (3, 'Corridoio 3', 1, 5, 10);
SET IDENTITY_INSERT Aisles OFF;


-- Cells
SET IDENTITY_INSERT CellStatuses ON;
INSERT INTO CellStatuses (Id, Description) VALUES (1, 'Vuota');
INSERT INTO CellStatuses (Id, Description) VALUES (2, 'Impegnata');
INSERT INTO CellStatuses (Id, Description) VALUES (3, 'Piena');
INSERT INTO CellStatuses (Id, Description) VALUES (4, 'Pieno su pieno');
INSERT INTO CellStatuses (Id, Description) VALUES (5, 'Vuoto su vuoto');
INSERT INTO CellStatuses (Id, Description) VALUES (6, 'Smezzata');
INSERT INTO CellStatuses (Id, Description) VALUES (7, 'Disabilitata');
SET IDENTITY_INSERT CellStatuses OFF;

SET IDENTITY_INSERT CellHeightClasses ON;
INSERT INTO CellHeightClasses (Id, Description, MinHeight, MaxHeight) VALUES (1, 'Cella max altezza 1300mm', 0, 1300);
INSERT INTO CellHeightClasses (Id, Description, MinHeight, MaxHeight) VALUES (2, 'Cella max altezza 1700mm', 1300, 1700);
SET IDENTITY_INSERT CellHeightClasses OFF;

SET IDENTITY_INSERT CellSizeClasses ON;
INSERT INTO CellSizeClasses (Id, Description, Width, Length) VALUES (1, 'Europallet', 800, 1200);
SET IDENTITY_INSERT CellSizeClasses OFF;

SET IDENTITY_INSERT CellWeightClasses ON;
INSERT INTO CellWeightClasses (Id, Description, MinWeight, MaxWeight) VALUES (1, 'Cella peso max 1000kg', 0, 1000);
SET IDENTITY_INSERT CellWeightClasses OFF;

SET IDENTITY_INSERT CellTypes ON;
INSERT INTO CellTypes (Id, CellHeightClassId, CellWeightClassId, CellSizeClassId, Description) VALUES (1, 2, 1, 1, 'Cella Europallet, max altezza 1300mm, max peso 1000kg');
INSERT INTO CellTypes (Id, CellHeightClassId, CellWeightClassId, CellSizeClassId, Description) VALUES (2, 1, 1, 1, 'Cella Europallet, max altezza 1700mm, max peso 1000kg');
SET IDENTITY_INSERT CellTypes OFF;

SET IDENTITY_INSERT Cells ON;
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (1, 1, 1, 1, 'L', 1, null, null, null, 1, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (2, 1, 1, 1, 'R', 2, null, null, null, 2, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (3, 1, 1, 2, 'L', 3, null, null, null, 3, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (4, 1, 1, 2, 'R', 4, null, null, null, 4, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (5, 1, 1, 3, 'L', 5, null, null, null, 5, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (6, 1, 1, 3, 'R', 6, null, null, null, 6, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (7, 1, 1, 4, 'L', 7, null, null, null, 7, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (8, 1, 1, 4, 'R', 8, null, null, null, 8, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (9, 1, 1, 5, 'L', 9, null, null, null, 9, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (10, 1, 1, 5, 'R', 10, null, null, null, 10, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (11, 1, 1, 6, 'L', 11, null, null, null, 11, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (12, 1, 1, 6, 'R', 12, null, null, null, 12, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (13, 1, 1, 7, 'L', 13, null, null, null, 13, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (14, 1, 1, 7, 'R', 14, null, null, null, 14, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (15, 1, 1, 8, 'L', 15, null, null, null, 15, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (16, 1, 1, 8, 'R', 16, null, null, null, 16, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (17, 1, 1, 9, 'L', 17, null, null, null, 17, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (18, 1, 1, 9, 'R', 18, null, null, null, 18, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (19, 1, 1, 10, 'L', 19, null, null, null, 19, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (20, 1, 1, 10, 'R', 20, null, null, null, 20, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (21, 1, 2, 1, 'L', 21, null, null, null, 21, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (22, 1, 2, 1, 'R', 22, null, null, null, 22, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (23, 1, 2, 2, 'L', 23, null, null, null, 23, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (24, 1, 2, 2, 'R', 24, null, null, null, 24, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (25, 1, 2, 3, 'L', 25, null, null, null, 25, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (26, 1, 2, 3, 'R', 26, null, null, null, 26, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (27, 1, 2, 4, 'L', 27, null, null, null, 27, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (28, 1, 2, 4, 'R', 28, null, null, null, 28, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (29, 1, 2, 5, 'L', 29, null, null, null, 29, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (30, 1, 2, 5, 'R', 30, null, null, null, 30, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (31, 1, 2, 6, 'L', 31, null, null, null, 31, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (32, 1, 2, 6, 'R', 32, null, null, null, 32, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (33, 1, 2, 7, 'L', 33, null, null, null, 33, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (34, 1, 2, 7, 'R', 34, null, null, null, 34, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (35, 1, 2, 8, 'L', 35, null, null, null, 35, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (36, 1, 2, 8, 'R', 36, null, null, null, 36, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (37, 1, 2, 9, 'L', 37, null, null, null, 37, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (38, 1, 2, 9, 'R', 38, null, null, null, 38, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (39, 1, 2, 10, 'L', 39, null, null, null, 39, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (40, 1, 2, 10, 'R', 40, null, null, null, 40, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (41, 1, 3, 1, 'L', 41, null, null, null, 41, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (42, 1, 3, 1, 'R', 42, null, null, null, 42, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (43, 1, 3, 2, 'L', 43, null, null, null, 43, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (44, 1, 3, 2, 'R', 44, null, null, null, 44, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (45, 1, 3, 3, 'L', 45, null, null, null, 45, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (46, 1, 3, 3, 'R', 46, null, null, null, 46, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (47, 1, 3, 4, 'L', 47, null, null, null, 47, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (48, 1, 3, 4, 'R', 48, null, null, null, 48, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (49, 1, 3, 5, 'L', 49, null, null, null, 49, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (50, 1, 3, 5, 'R', 50, null, null, null, 50, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (51, 1, 3, 6, 'L', 51, null, null, null, 51, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (52, 1, 3, 6, 'R', 52, null, null, null, 52, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (53, 1, 3, 7, 'L', 53, null, null, null, 53, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (54, 1, 3, 7, 'R', 54, null, null, null, 54, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (55, 1, 3, 8, 'L', 55, null, null, null, 55, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (56, 1, 3, 8, 'R', 56, null, null, null, 56, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (57, 1, 3, 9, 'L', 57, null, null, null, 57, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (58, 1, 3, 9, 'R', 58, null, null, null, 58, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (59, 1, 3, 10, 'L', 59, null, null, null, 59, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (60, 1, 3, 10, 'R', 60, null, null, null, 60, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (61, 1, 4, 1, 'L', 61, null, null, null, 61, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (62, 1, 4, 1, 'R', 62, null, null, null, 62, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (63, 1, 4, 2, 'L', 63, null, null, null, 63, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (64, 1, 4, 2, 'R', 64, null, null, null, 64, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (65, 1, 4, 3, 'L', 65, null, null, null, 65, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (66, 1, 4, 3, 'R', 66, null, null, null, 66, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (67, 1, 4, 4, 'L', 67, null, null, null, 67, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (68, 1, 4, 4, 'R', 68, null, null, null, 68, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (69, 1, 4, 5, 'L', 69, null, null, null, 69, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (70, 1, 4, 5, 'R', 70, null, null, null, 70, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (71, 1, 4, 6, 'L', 71, null, null, null, 71, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (72, 1, 4, 6, 'R', 72, null, null, null, 72, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (73, 1, 4, 7, 'L', 73, null, null, null, 73, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (74, 1, 4, 7, 'R', 74, null, null, null, 74, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (75, 1, 4, 8, 'L', 75, null, null, null, 75, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (76, 1, 4, 8, 'R', 76, null, null, null, 76, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (77, 1, 4, 9, 'L', 77, null, null, null, 77, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (78, 1, 4, 9, 'R', 78, null, null, null, 78, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (79, 1, 4, 10, 'L', 79, null, null, null, 79, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (80, 1, 4, 10, 'R', 80, null, null, null, 80, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (81, 1, 5, 1, 'L', 81, null, null, null, 81, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (82, 1, 5, 1, 'R', 82, null, null, null, 82, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (83, 1, 5, 2, 'L', 83, null, null, null, 83, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (84, 1, 5, 2, 'R', 84, null, null, null, 84, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (85, 1, 5, 3, 'L', 85, null, null, null, 85, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (86, 1, 5, 3, 'R', 86, null, null, null, 86, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (87, 1, 5, 4, 'L', 87, null, null, null, 87, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (88, 1, 5, 4, 'R', 88, null, null, null, 88, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (89, 1, 5, 5, 'L', 89, null, null, null, 89, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (90, 1, 5, 5, 'R', 90, null, null, null, 90, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (91, 1, 5, 6, 'L', 91, null, null, null, 91, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (92, 1, 5, 6, 'R', 92, null, null, null, 92, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (93, 1, 5, 7, 'L', 93, null, null, null, 93, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (94, 1, 5, 7, 'R', 94, null, null, null, 94, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (95, 1, 5, 8, 'L', 95, null, null, null, 95, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (96, 1, 5, 8, 'R', 96, null, null, null, 96, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (97, 1, 5, 9, 'L', 97, null, null, null, 97, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (98, 1, 5, 9, 'R', 98, null, null, null, 98, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (99, 1, 5, 10, 'L', 99, null, null, null, 99, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (100, 1, 5, 10, 'R', 100, null, null, null, 100, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (101, 2, 1, 1, 'L', 1, null, null, null, 1, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (102, 2, 1, 1, 'R', 2, null, null, null, 2, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (103, 2, 1, 2, 'L', 3, null, null, null, 3, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (104, 2, 1, 2, 'R', 4, null, null, null, 4, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (105, 2, 1, 3, 'L', 5, null, null, null, 5, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (106, 2, 1, 3, 'R', 6, null, null, null, 6, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (107, 2, 1, 4, 'L', 7, null, null, null, 7, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (108, 2, 1, 4, 'R', 8, null, null, null, 8, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (109, 2, 1, 5, 'L', 9, null, null, null, 9, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (110, 2, 1, 5, 'R', 10, null, null, null, 10, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (111, 2, 1, 6, 'L', 11, null, null, null, 11, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (112, 2, 1, 6, 'R', 12, null, null, null, 12, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (113, 2, 1, 7, 'L', 13, null, null, null, 13, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (114, 2, 1, 7, 'R', 14, null, null, null, 14, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (115, 2, 1, 8, 'L', 15, null, null, null, 15, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (116, 2, 1, 8, 'R', 16, null, null, null, 16, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (117, 2, 1, 9, 'L', 17, null, null, null, 17, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (118, 2, 1, 9, 'R', 18, null, null, null, 18, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (119, 2, 1, 10, 'L', 19, null, null, null, 19, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (120, 2, 1, 10, 'R', 20, null, null, null, 20, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (121, 2, 2, 1, 'L', 21, null, null, null, 21, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (122, 2, 2, 1, 'R', 22, null, null, null, 22, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (123, 2, 2, 2, 'L', 23, null, null, null, 23, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (124, 2, 2, 2, 'R', 24, null, null, null, 24, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (125, 2, 2, 3, 'L', 25, null, null, null, 25, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (126, 2, 2, 3, 'R', 26, null, null, null, 26, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (127, 2, 2, 4, 'L', 27, null, null, null, 27, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (128, 2, 2, 4, 'R', 28, null, null, null, 28, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (129, 2, 2, 5, 'L', 29, null, null, null, 29, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (130, 2, 2, 5, 'R', 30, null, null, null, 30, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (131, 2, 2, 6, 'L', 31, null, null, null, 31, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (132, 2, 2, 6, 'R', 32, null, null, null, 32, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (133, 2, 2, 7, 'L', 33, null, null, null, 33, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (134, 2, 2, 7, 'R', 34, null, null, null, 34, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (135, 2, 2, 8, 'L', 35, null, null, null, 35, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (136, 2, 2, 8, 'R', 36, null, null, null, 36, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (137, 2, 2, 9, 'L', 37, null, null, null, 37, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (138, 2, 2, 9, 'R', 38, null, null, null, 38, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (139, 2, 2, 10, 'L', 39, null, null, null, 39, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (140, 2, 2, 10, 'R', 40, null, null, null, 40, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (141, 2, 3, 1, 'L', 41, null, null, null, 41, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (142, 2, 3, 1, 'R', 42, null, null, null, 42, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (143, 2, 3, 2, 'L', 43, null, null, null, 43, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (144, 2, 3, 2, 'R', 44, null, null, null, 44, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (145, 2, 3, 3, 'L', 45, null, null, null, 45, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (146, 2, 3, 3, 'R', 46, null, null, null, 46, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (147, 2, 3, 4, 'L', 47, null, null, null, 47, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (148, 2, 3, 4, 'R', 48, null, null, null, 48, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (149, 2, 3, 5, 'L', 49, null, null, null, 49, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (150, 2, 3, 5, 'R', 50, null, null, null, 50, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (151, 2, 3, 6, 'L', 51, null, null, null, 51, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (152, 2, 3, 6, 'R', 52, null, null, null, 52, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (153, 2, 3, 7, 'L', 53, null, null, null, 53, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (154, 2, 3, 7, 'R', 54, null, null, null, 54, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (155, 2, 3, 8, 'L', 55, null, null, null, 55, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (156, 2, 3, 8, 'R', 56, null, null, null, 56, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (157, 2, 3, 9, 'L', 57, null, null, null, 57, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (158, 2, 3, 9, 'R', 58, null, null, null, 58, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (159, 2, 3, 10, 'L', 59, null, null, null, 59, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (160, 2, 3, 10, 'R', 60, null, null, null, 60, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (161, 2, 4, 1, 'L', 61, null, null, null, 61, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (162, 2, 4, 1, 'R', 62, null, null, null, 62, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (163, 2, 4, 2, 'L', 63, null, null, null, 63, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (164, 2, 4, 2, 'R', 64, null, null, null, 64, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (165, 2, 4, 3, 'L', 65, null, null, null, 65, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (166, 2, 4, 3, 'R', 66, null, null, null, 66, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (167, 2, 4, 4, 'L', 67, null, null, null, 67, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (168, 2, 4, 4, 'R', 68, null, null, null, 68, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (169, 2, 4, 5, 'L', 69, null, null, null, 69, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (170, 2, 4, 5, 'R', 70, null, null, null, 70, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (171, 2, 4, 6, 'L', 71, null, null, null, 71, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (172, 2, 4, 6, 'R', 72, null, null, null, 72, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (173, 2, 4, 7, 'L', 73, null, null, null, 73, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (174, 2, 4, 7, 'R', 74, null, null, null, 74, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (175, 2, 4, 8, 'L', 75, null, null, null, 75, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (176, 2, 4, 8, 'R', 76, null, null, null, 76, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (177, 2, 4, 9, 'L', 77, null, null, null, 77, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (178, 2, 4, 9, 'R', 78, null, null, null, 78, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (179, 2, 4, 10, 'L', 79, null, null, null, 79, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (180, 2, 4, 10, 'R', 80, null, null, null, 80, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (181, 2, 5, 1, 'L', 81, null, null, null, 81, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (182, 2, 5, 1, 'R', 82, null, null, null, 82, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (183, 2, 5, 2, 'L', 83, null, null, null, 83, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (184, 2, 5, 2, 'R', 84, null, null, null, 84, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (185, 2, 5, 3, 'L', 85, null, null, null, 85, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (186, 2, 5, 3, 'R', 86, null, null, null, 86, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (187, 2, 5, 4, 'L', 87, null, null, null, 87, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (188, 2, 5, 4, 'R', 88, null, null, null, 88, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (189, 2, 5, 5, 'L', 89, null, null, null, 89, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (190, 2, 5, 5, 'R', 90, null, null, null, 90, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (191, 2, 5, 6, 'L', 91, null, null, null, 91, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (192, 2, 5, 6, 'R', 92, null, null, null, 92, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (193, 2, 5, 7, 'L', 93, null, null, null, 93, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (194, 2, 5, 7, 'R', 94, null, null, null, 94, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (195, 2, 5, 8, 'L', 95, null, null, null, 95, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (196, 2, 5, 8, 'R', 96, null, null, null, 96, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (197, 2, 5, 9, 'L', 97, null, null, null, 97, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (198, 2, 5, 9, 'R', 98, null, null, null, 98, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (199, 2, 5, 10, 'L', 99, null, null, null, 99, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (200, 2, 5, 10, 'R', 100, null, null, null, 100, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (201, 3, 1, 1, 'L', 1, null, null, null, 1, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (202, 3, 1, 1, 'R', 2, null, null, null, 2, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (203, 3, 1, 2, 'L', 3, null, null, null, 3, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (204, 3, 1, 2, 'R', 4, null, null, null, 4, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (205, 3, 1, 3, 'L', 5, null, null, null, 5, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (206, 3, 1, 3, 'R', 6, null, null, null, 6, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (207, 3, 1, 4, 'L', 7, null, null, null, 7, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (208, 3, 1, 4, 'R', 8, null, null, null, 8, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (209, 3, 1, 5, 'L', 9, null, null, null, 9, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (210, 3, 1, 5, 'R', 10, null, null, null, 10, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (211, 3, 1, 6, 'L', 11, null, null, null, 11, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (212, 3, 1, 6, 'R', 12, null, null, null, 12, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (213, 3, 1, 7, 'L', 13, null, null, null, 13, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (214, 3, 1, 7, 'R', 14, null, null, null, 14, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (215, 3, 1, 8, 'L', 15, null, null, null, 15, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (216, 3, 1, 8, 'R', 16, null, null, null, 16, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (217, 3, 1, 9, 'L', 17, null, null, null, 17, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (218, 3, 1, 9, 'R', 18, null, null, null, 18, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (219, 3, 1, 10, 'L', 19, null, null, null, 19, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (220, 3, 1, 10, 'R', 20, null, null, null, 20, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (221, 3, 2, 1, 'L', 21, null, null, null, 21, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (222, 3, 2, 1, 'R', 22, null, null, null, 22, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (223, 3, 2, 2, 'L', 23, null, null, null, 23, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (224, 3, 2, 2, 'R', 24, null, null, null, 24, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (225, 3, 2, 3, 'L', 25, null, null, null, 25, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (226, 3, 2, 3, 'R', 26, null, null, null, 26, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (227, 3, 2, 4, 'L', 27, null, null, null, 27, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (228, 3, 2, 4, 'R', 28, null, null, null, 28, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (229, 3, 2, 5, 'L', 29, null, null, null, 29, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (230, 3, 2, 5, 'R', 30, null, null, null, 30, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (231, 3, 2, 6, 'L', 31, null, null, null, 31, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (232, 3, 2, 6, 'R', 32, null, null, null, 32, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (233, 3, 2, 7, 'L', 33, null, null, null, 33, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (234, 3, 2, 7, 'R', 34, null, null, null, 34, 1, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (235, 3, 2, 8, 'L', 35, null, null, null, 35, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (236, 3, 2, 8, 'R', 36, null, null, null, 36, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (237, 3, 2, 9, 'L', 37, null, null, null, 37, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (238, 3, 2, 9, 'R', 38, null, null, null, 38, 1, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (239, 3, 2, 10, 'L', 39, null, null, null, 39, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (240, 3, 2, 10, 'R', 40, null, null, null, 40, 1, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (241, 3, 3, 1, 'L', 41, null, null, null, 41, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (242, 3, 3, 1, 'R', 42, null, null, null, 42, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (243, 3, 3, 2, 'L', 43, null, null, null, 43, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (244, 3, 3, 2, 'R', 44, null, null, null, 44, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (245, 3, 3, 3, 'L', 45, null, null, null, 45, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (246, 3, 3, 3, 'R', 46, null, null, null, 46, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (247, 3, 3, 4, 'L', 47, null, null, null, 47, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (248, 3, 3, 4, 'R', 48, null, null, null, 48, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (249, 3, 3, 5, 'L', 49, null, null, null, 49, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (250, 3, 3, 5, 'R', 50, null, null, null, 50, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (251, 3, 3, 6, 'L', 51, null, null, null, 51, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (252, 3, 3, 6, 'R', 52, null, null, null, 52, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (253, 3, 3, 7, 'L', 53, null, null, null, 53, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (254, 3, 3, 7, 'R', 54, null, null, null, 54, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (255, 3, 3, 8, 'L', 55, null, null, null, 55, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (256, 3, 3, 8, 'R', 56, null, null, null, 56, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (257, 3, 3, 9, 'L', 57, null, null, null, 57, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (258, 3, 3, 9, 'R', 58, null, null, null, 58, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (259, 3, 3, 10, 'L', 59, null, null, null, 59, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (260, 3, 3, 10, 'R', 60, null, null, null, 60, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (261, 3, 4, 1, 'L', 61, null, null, null, 61, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (262, 3, 4, 1, 'R', 62, null, null, null, 62, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (263, 3, 4, 2, 'L', 63, null, null, null, 63, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (264, 3, 4, 2, 'R', 64, null, null, null, 64, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (265, 3, 4, 3, 'L', 65, null, null, null, 65, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (266, 3, 4, 3, 'R', 66, null, null, null, 66, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (267, 3, 4, 4, 'L', 67, null, null, null, 67, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (268, 3, 4, 4, 'R', 68, null, null, null, 68, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (269, 3, 4, 5, 'L', 69, null, null, null, 69, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (270, 3, 4, 5, 'R', 70, null, null, null, 70, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (271, 3, 4, 6, 'L', 71, null, null, null, 71, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (272, 3, 4, 6, 'R', 72, null, null, null, 72, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (273, 3, 4, 7, 'L', 73, null, null, null, 73, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (274, 3, 4, 7, 'R', 74, null, null, null, 74, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (275, 3, 4, 8, 'L', 75, null, null, null, 75, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (276, 3, 4, 8, 'R', 76, null, null, null, 76, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (277, 3, 4, 9, 'L', 77, null, null, null, 77, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (278, 3, 4, 9, 'R', 78, null, null, null, 78, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (279, 3, 4, 10, 'L', 79, null, null, null, 79, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (280, 3, 4, 10, 'R', 80, null, null, null, 80, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (281, 3, 5, 1, 'L', 81, null, null, null, 81, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (282, 3, 5, 1, 'R', 82, null, null, null, 82, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (283, 3, 5, 2, 'L', 83, null, null, null, 83, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (284, 3, 5, 2, 'R', 84, null, null, null, 84, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (285, 3, 5, 3, 'L', 85, null, null, null, 85, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (286, 3, 5, 3, 'R', 86, null, null, null, 86, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (287, 3, 5, 4, 'L', 87, null, null, null, 87, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (288, 3, 5, 4, 'R', 88, null, null, null, 88, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (289, 3, 5, 5, 'L', 89, null, null, null, 89, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (290, 3, 5, 5, 'R', 90, null, null, null, 90, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (291, 3, 5, 6, 'L', 91, null, null, null, 91, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (292, 3, 5, 6, 'R', 92, null, null, null, 92, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (293, 3, 5, 7, 'L', 93, null, null, null, 93, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (294, 3, 5, 7, 'R', 94, null, null, null, 94, 2, 'A', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (295, 3, 5, 8, 'L', 95, null, null, null, 95, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (296, 3, 5, 8, 'R', 96, null, null, null, 96, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (297, 3, 5, 9, 'L', 97, null, null, null, 97, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (298, 3, 5, 9, 'R', 98, null, null, null, 98, 2, 'B', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (299, 3, 5, 10, 'L', 99, null, null, null, 99, 2, 'C', 1);
INSERT INTO Cells (Id, AisleId, Floor, [Column], Side, CellNumber, XCoordinate, YCoordinate, ZCoordinate, Priority, CellTypeId, Class, CellStatusId) VALUES (300, 3, 5, 10, 'R', 100, null, null, null, 100, 2, 'C', 1);
SET IDENTITY_INSERT Cells OFF;

SET IDENTITY_INSERT CellConfigurations ON;
INSERT INTO CellConfigurations (Id, Description) VALUES (1, '1 pallet alto presente');
INSERT INTO CellConfigurations (Id, Description) VALUES (2, '1 pallet basso presente');
SET IDENTITY_INSERT CellConfigurations OFF;

INSERT INTO CellConfigurationCellTypes (CellConfigurationId, CellTypeId, Priority) VALUES (1, 1, 1);
INSERT INTO CellConfigurationCellTypes (CellConfigurationId, CellTypeId, Priority) VALUES (2, 1, 2);
INSERT INTO CellConfigurationCellTypes (CellConfigurationId, CellTypeId, Priority) VALUES (2, 2, 1);

SET IDENTITY_INSERT CellPositions ON;
INSERT INTO CellPositions (Id, XOffset, YOffset, ZOffset, Description) VALUES (1, null, null, null, 'Posizione pallet centrato su cella');
SET IDENTITY_INSERT CellPositions OFF;


-- Loading Units
SET IDENTITY_INSERT LoadingUnitStatuses ON;
INSERT INTO LoadingUnitStatuses (Id, Description) VALUES (1, 'Impegnata');
INSERT INTO LoadingUnitStatuses (Id, Description) VALUES (2, 'Bloccata');
INSERT INTO LoadingUnitStatuses (Id, Description) VALUES (3, 'Disponibile');
SET IDENTITY_INSERT LoadingUnitStatuses OFF;

SET IDENTITY_INSERT LoadingUnitWeightClasses ON;
INSERT INTO LoadingUnitWeightClasses (Id, Description, MinWeight, MaxWeight) VALUES (1, 'Pallet peso max 1000kg', 0, 1000);
SET IDENTITY_INSERT LoadingUnitWeightClasses OFF;

SET IDENTITY_INSERT LoadingUnitSizeClasses ON;
INSERT INTO LoadingUnitSizeClasses (Id, Description, Width, Length, BayOffset, Lift, BayForksUnthread, CellForksUnthread) VALUES (1, 'Europallet', 800, 1200, 0, 0, 0, 0);
SET IDENTITY_INSERT LoadingUnitSizeClasses OFF;

SET IDENTITY_INSERT LoadingUnitHeightClasses ON;
INSERT INTO LoadingUnitHeightClasses (Id, Description, MinHeight, MaxHeight) VALUES (1, 'Pallet altezza max 1300mm', 0, 1300);
INSERT INTO LoadingUnitHeightClasses (Id, Description, MinHeight, MaxHeight) VALUES (2, 'Pallet altezza max 1700mm', 1300, 1700);
SET IDENTITY_INSERT LoadingUnitHeightClasses OFF;

SET IDENTITY_INSERT LoadingUnitTypes ON;
INSERT INTO LoadingUnitTypes (Id, LoadingUnitHeightClassId, LoadingUnitWeightClassId, LoadingUnitSizeClassId, Description) VALUES (1, 1, 1, 1, 'Europallet, max altezza 1700mm, max peso 1000kg');
INSERT INTO LoadingUnitTypes (Id, LoadingUnitHeightClassId, LoadingUnitWeightClassId, LoadingUnitSizeClassId, Description) VALUES (2, 2, 1, 1, 'Europallet, max altezza 1300mm, max peso 1000kg');
SET IDENTITY_INSERT LoadingUnitTypes OFF;

INSERT INTO LoadingUnitTypesAisles (AisleId, LoadingUnitTypeId) VALUES (1, 1);
INSERT INTO LoadingUnitTypesAisles (AisleId, LoadingUnitTypeId) VALUES (2, 1);
INSERT INTO LoadingUnitTypesAisles (AisleId, LoadingUnitTypeId) VALUES (3, 1);
INSERT INTO LoadingUnitTypesAisles (AisleId, LoadingUnitTypeId) VALUES (1, 2);
INSERT INTO LoadingUnitTypesAisles (AisleId, LoadingUnitTypeId) VALUES (2, 2);
INSERT INTO LoadingUnitTypesAisles (AisleId, LoadingUnitTypeId) VALUES (3, 2);

INSERT INTO CellConfigurationCellPositionLoadingUnitTypes (CellPositionId, CellConfigurationId, LoadingUnitTypeId, Priority) VALUES (1, 1, 1, 1);
INSERT INTO CellConfigurationCellPositionLoadingUnitTypes (CellPositionId, CellConfigurationId, LoadingUnitTypeId, Priority) VALUES (1, 2, 2, 1);


--Items
SET IDENTITY_INSERT ItemManagementTypes ON;
INSERT INTO ItemManagementTypes (Id, Description) VALUES (1, 'FIFO');
INSERT INTO ItemManagementTypes (Id, Description) VALUES (2, 'Volume');
SET IDENTITY_INSERT ItemManagementTypes OFF;

SET IDENTITY_INSERT MeasureUnits ON;
INSERT INTO MeasureUnits (Id, Description) VALUES (1, 'Pz');
SET IDENTITY_INSERT MeasureUnits OFF;

SET IDENTITY_INSERT Items ON;
INSERT INTO Items (Id, Code, Description, Class, MeasureUnitId, Width, Length, Height, ItemManagementTypeId, FifoTimeStore, FifoTimePick, ReorderPoint, ReorderQuantity, AverageWeight, PickTolerance, StoreTolerance, InventoryTolerance, CreationDate, LastModificationDate, InventoryDate, LastPickDate, LastStoreDate, Image, Note) VALUES (1, 'U000498', '000498        FRESA SMUSSO PUNTA KABA', 'A', 1, null, null, null, 2, null, null, null, null, null, null, null, null, '2018-07-24 17:35:42.6166667', null, null, null, null, null, null);
INSERT INTO Items (Id, Code, Description, Class, MeasureUnitId, Width, Length, Height, ItemManagementTypeId, FifoTimeStore, FifoTimePick, ReorderPoint, ReorderQuantity, AverageWeight, PickTolerance, StoreTolerance, InventoryTolerance, CreationDate, LastModificationDate, InventoryDate, LastPickDate, LastStoreDate, Image, Note) VALUES (2, 'U000499', '000499        FRESA SMUSSO PUNTA KESO', 'A', 1, null, null, null, 2, null, null, null, null, null, null, null, null, '2018-07-24 17:35:42.6266667', null, null, null, null, null, null);
INSERT INTO Items (Id, Code, Description, Class, MeasureUnitId, Width, Length, Height, ItemManagementTypeId, FifoTimeStore, FifoTimePick, ReorderPoint, ReorderQuantity, AverageWeight, PickTolerance, StoreTolerance, InventoryTolerance, CreationDate, LastModificationDate, InventoryDate, LastPickDate, LastStoreDate, Image, Note) VALUES (3, 'U000524', '000524        FRESA DESTRA 50X50X22 Z=12', 'B', 1, null, null, null, 2, null, null, null, null, null, null, null, null, '2018-07-24 17:35:42.6333333', null, null, null, null, null, null);
INSERT INTO Items (Id, Code, Description, Class, MeasureUnitId, Width, Length, Height, ItemManagementTypeId, FifoTimeStore, FifoTimePick, ReorderPoint, ReorderQuantity, AverageWeight, PickTolerance, StoreTolerance, InventoryTolerance, CreationDate, LastModificationDate, InventoryDate, LastPickDate, LastStoreDate, Image, Note) VALUES (4, 'U000578', '000578        FRESA DORSI VAC91', 'B', 1, null, null, null, 2, null, null, null, null, null, null, null, null, '2018-07-24 17:35:42.6400000', null, null, null, null, null, null);
INSERT INTO Items (Id, Code, Description, Class, MeasureUnitId, Width, Length, Height, ItemManagementTypeId, FifoTimeStore, FifoTimePick, ReorderPoint, ReorderQuantity, AverageWeight, PickTolerance, StoreTolerance, InventoryTolerance, CreationDate, LastModificationDate, InventoryDate, LastPickDate, LastStoreDate, Image, Note) VALUES (5, 'U000585', '000585        FR.PROF.COSTANTE FR.LAT.', 'C', 1, null, null, null, 2, null, null, null, null, null, null, null, null, '2018-07-24 17:35:42.6466667', null, null, null, null, null, null);
INSERT INTO Items (Id, Code, Description, Class, MeasureUnitId, Width, Length, Height, ItemManagementTypeId, FifoTimeStore, FifoTimePick, ReorderPoint, ReorderQuantity, AverageWeight, PickTolerance, StoreTolerance, InventoryTolerance, CreationDate, LastModificationDate, InventoryDate, LastPickDate, LastStoreDate, Image, Note) VALUES (6, 'U000640', '000640        FRESA A PLACCHE RIPORTATE', 'C', 1, null, null, null, 2, null, null, null, null, null, null, null, null, '2018-07-24 17:35:42.6533333', null, null, null, null, null, null);
SET IDENTITY_INSERT Items OFF;

INSERT INTO ItemsAreas (ItemId, AreaId) VALUES (1, 1);
INSERT INTO ItemsAreas (ItemId, AreaId) VALUES (2, 1);
INSERT INTO ItemsAreas (ItemId, AreaId) VALUES (3, 1);
INSERT INTO ItemsAreas (ItemId, AreaId) VALUES (4, 1);
INSERT INTO ItemsAreas (ItemId, AreaId) VALUES (5, 1);
INSERT INTO ItemsAreas (ItemId, AreaId) VALUES (6, 1);


-- Compartments
SET IDENTITY_INSERT MaterialStatuses ON;
INSERT INTO MaterialStatuses (Id, Description) VALUES (1, 'Disponibile');
INSERT INTO MaterialStatuses (Id, Description) VALUES (2, 'Attesa verifica');
INSERT INTO MaterialStatuses (Id, Description) VALUES (3, 'Scaduto');
INSERT INTO MaterialStatuses (Id, Description) VALUES (4, 'Bloccato');
SET IDENTITY_INSERT MaterialStatuses OFF;

SET IDENTITY_INSERT PackageTypes ON;
INSERT INTO PackageTypes (Id, Description) VALUES (1, 'Sciolto');
INSERT INTO PackageTypes (Id, Description) VALUES (2, 'Confezioni piccole');
INSERT INTO PackageTypes (Id, Description) VALUES (3, 'Confezioni medie');
INSERT INTO PackageTypes (Id, Description) VALUES (4, 'Scatole');
SET IDENTITY_INSERT PackageTypes OFF; 

SET IDENTITY_INSERT CompartmentStatuses ON;
INSERT INTO CompartmentStatuses (Id, Description) VALUES (1, 'Libero');
INSERT INTO CompartmentStatuses (Id, Description) VALUES (2, 'Occupato');
INSERT INTO CompartmentStatuses (Id, Description) VALUES (3, 'Vuoto');
INSERT INTO CompartmentStatuses (Id, Description) VALUES (4, 'Pieno');
INSERT INTO CompartmentStatuses (Id, Description) VALUES (5, 'Impegnato');
INSERT INTO CompartmentStatuses (Id, Description) VALUES (6, 'Disabilitato');
SET IDENTITY_INSERT CompartmentStatuses OFF;


-- ItemLists
SET IDENTITY_INSERT ItemListTypes ON;
INSERT INTO ItemListTypes (Id, Description) VALUES (1, 'Prelievo');
INSERT INTO ItemListTypes (Id, Description) VALUES (2, 'Versamento');
INSERT INTO ItemListTypes (Id, Description) VALUES (3, 'Inventario');
SET IDENTITY_INSERT ItemListTypes OFF;

SET IDENTITY_INSERT ItemListStatuses ON;
INSERT INTO ItemListStatuses (Id, Description) VALUES (1, 'Attesa');
INSERT INTO ItemListStatuses (Id, Description) VALUES (2, 'Esecuzione');
INSERT INTO ItemListStatuses (Id, Description) VALUES (3, 'Completata');
INSERT INTO ItemListStatuses (Id, Description) VALUES (4, 'Incompleta');
INSERT INTO ItemListStatuses (Id, Description) VALUES (5, 'Sospesa');
SET IDENTITY_INSERT ItemListStatuses OFF;

SET IDENTITY_INSERT ItemListRowStatuses ON;
INSERT INTO ItemListRowStatuses (Id, Description) VALUES (1, 'Attesa');
INSERT INTO ItemListRowStatuses (Id, Description) VALUES (2, 'Esecuzione');
INSERT INTO ItemListRowStatuses (Id, Description) VALUES (3, 'Completata');
INSERT INTO ItemListRowStatuses (Id, Description) VALUES (4, 'Incompleta');
INSERT INTO ItemListRowStatuses (Id, Description) VALUES (5, 'Sospesa');
SET IDENTITY_INSERT ItemListRowStatuses OFF;