resources:
- repo: self
  fetchDepth: 15
queue:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - VerticalWarehouses
    - WMS
    - Common
    include:
    - Common\DataModels
    - Common\EF

variables:
  CloudInitialCatalog: 'FerrettoWmsDb_Testing_$(Build.BuildId)'


steps:

- task: andrewlackenby.sql-toolkit.runsqlcommand.RunSqlCommand@2
  displayName: 'Create cloud db'
  inputs:
    serverName: 'rd-ferrettogroup.database.windows.net'
    databaseName: master
    sqlCommand: 'CREATE DATABASE $(CloudInitialCatalog);'
    userName: admin_rd_ferrettogroup
    userPassword: Ferretto2019!
    queryTimeout: 240


- script: 'dotnet ef database update --verbose'
  workingDirectory: Common/EF
  failOnStderr: true
  displayName: 'dotnet ef database update'
  continueOnError: true
  env:
    NETCORE_ENVIRONMENT: CloudBuild
    cloudInitialCatalog: '$(CloudInitialCatalog)'


- task: andrewlackenby.sql-toolkit.runsinglesqlscript.RunSingleSqlScript@2
  displayName: 'Apply db seed'
  inputs:
    sqlScript: Common/EF/Seeds/Dev.InitDb.sql
    serverName: 'rd-ferrettogroup.database.windows.net'
    databaseName: '$(CloudInitialCatalog)'
    userName: admin_rd_ferrettogroup
    userPassword: Ferretto2019!
    queryTimeout: 30


- task: andrewlackenby.sql-toolkit.runsqlcommand.RunSqlCommand@2
  displayName: 'Drop cloud db'
  inputs:
    serverName: 'rd-ferrettogroup.database.windows.net'
    databaseName: master
    sqlCommand: 'DROP DATABASE $(CloudInitialCatalog);'
    userName: admin_rd_ferrettogroup
    userPassword: Ferretto2019!
    queryTimeout: 120
    condition: always()
