resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - 'VerticalWarehouses'
    - 'WMS\App'
    include:
    - 'VerticalWarehouses\Machine Automation Service\Hubs'
    - 'VerticalWarehouses\Machine Automation Service\Contracts'
    - 'VerticalWarehouses\Panel PC UI\ConsoleApp.Mock'

steps:


- template: azure-pipeline-wms-services-template.yml
  parameters:
    BuildConfiguration: 'Debug'
    RestoreBuildProjects: '**/Ferretto.@(VW.PanelPC.ConsoleApp.Mock|WMS.Data.WebAPI).csproj'
    TestProjects: 'WMS/@(Data|Scheduler)/**/*.Tests.csproj'
    TargetFramework: 'netcoreapp2.2'
