resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - VerticalWarehouses
    - WMS\Data
    - WMS\Scheduler

steps:

- template: azure-pipeline-wms-ui-template.yml
  parameters:
    BuildConfiguration: 'DebugWmsUI'
    BuildProjectConfiguration: 'Debug'
    BuildPlatform: 'any cpu'
