resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - VerticalWarehouses
    - WMS\App


steps:


- template: azure-pipeline-wms-services-template.yml
  parameters:
    BuildConfiguration: 'Debug'
    RestoreBuildProjects: 'WMS/**/(Ferretto.WMS.Data.WebAPI.csproj|Ferretto.WMS.AutomationServiceMock.csproj)'
    TestProjects: 'WMS/Data/**/*.Tests.csproj'
    TargetFramework: 'netcoreapp2.1'
