resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - VerticalWarehouses
    - WMS\App

variables:
  BuildConfiguration: 'Debug'
  RestoreBuildProjects: 'WMS/Data/**/*.csproj'
  TestProjects: 'WMS/Data/**/*.Tests.csproj'
  TargetFramework: 'netcoreapp2.1'

steps:


- template: azure-pipeline-wms-services-dev-template.yml
