using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1124:Do not use regions", Justification = "Agreed")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Agreed")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File should have header", Justification = "Agreed")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "Agreed")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "Agreed")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1200:Using directives should be placed correctly", Justification = "Agreed")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA000", Justification = "Agreed")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Agreed")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1812", Justification = "Agreed")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031", Justification = "Agreed")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Agreed")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Agreed")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Agreed")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Dispose Ownership Transfer")]
[assembly: SuppressMessage("Style", "IDE0011:Add braces", Justification = "Agreed")]
[assembly: SuppressMessage("Style", "IDE0009:Member access should be qualified.", Justification = "Agreed")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "Agreed")]
