//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.VW.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallationApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallationApp() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.VW.Resources.InstallationApp", typeof(InstallationApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Acceptable weight tolerance [%]:.
        /// </summary>
        public static string AcceptableWeightTolerance {
            get {
                return ResourceManager.GetString("AcceptableWeightTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Active rays quantity:.
        /// </summary>
        public static string ActiveRaysQuantity {
            get {
                return ResourceManager.GetString("ActiveRaysQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Actual position:.
        /// </summary>
        public static string ActualPosition {
            get {
                return ResourceManager.GetString("ActualPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anti intrusion gate bay 1.
        /// </summary>
        public static string AntiIntrusionGate {
            get {
                return ResourceManager.GetString("AntiIntrusionGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anti intrusion gate bay 2.
        /// </summary>
        public static string AntiIntrusionGate2 {
            get {
                return ResourceManager.GetString("AntiIntrusionGate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anti intrusion gate bay 3.
        /// </summary>
        public static string AntiIntrusionGate3 {
            get {
                return ResourceManager.GetString("AntiIntrusionGate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Auto.
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Axis Calibrated Successfully.
        /// </summary>
        public static string AxisCalibratedSuccessfully {
            get {
                return ResourceManager.GetString("AxisCalibratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Axis Not Calibrated Yet.
        /// </summary>
        public static string AxisNotCalibratedYet {
            get {
                return ResourceManager.GetString("AxisNotCalibratedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Backward.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Backward.
        /// </summary>
        public static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bays and height control.
        /// </summary>
        public static string Bays {
            get {
                return ResourceManager.GetString("Bays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Belt Burnishing.
        /// </summary>
        public static string BeltBurnishing {
            get {
                return ResourceManager.GetString("BeltBurnishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Belt burnishing.
        /// </summary>
        public static string BeltBurnishingDone {
            get {
                return ResourceManager.GetString("BeltBurnishingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Brake Resistance Overtemperature.
        /// </summary>
        public static string BrakeResistanceOvertemperature {
            get {
                return ResourceManager.GetString("BrakeResistanceOvertemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cell correction [mm]:.
        /// </summary>
        public static string CellCorrection {
            get {
                return ResourceManager.GetString("CellCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current cell&apos;s height [mm]:.
        /// </summary>
        public static string CellHeight {
            get {
                return ResourceManager.GetString("CellHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cell position verified.
        /// </summary>
        public static string CellPositionDone {
            get {
                return ResourceManager.GetString("CellPositionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cells  position control.
        /// </summary>
        public static string CellsControl {
            get {
                return ResourceManager.GetString("CellsControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cells&apos; Panel Control.
        /// </summary>
        public static string CellsPanelControl {
            get {
                return ResourceManager.GetString("CellsPanelControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CellsSideControlButton.
        /// </summary>
        public static string CellsSideControlButton {
            get {
                return ResourceManager.GetString("CellsSideControlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CellsSideControlCorrection.
        /// </summary>
        public static string CellsSideControlCorrection {
            get {
                return ResourceManager.GetString("CellsSideControlCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CellsSideControlDescription.
        /// </summary>
        public static string CellsSideControlDescription {
            get {
                return ResourceManager.GetString("CellsSideControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CellsSideControlFinalCell.
        /// </summary>
        public static string CellsSideControlFinalCell {
            get {
                return ResourceManager.GetString("CellsSideControlFinalCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CellsSideControlInitialCell.
        /// </summary>
        public static string CellsSideControlInitialCell {
            get {
                return ResourceManager.GetString("CellsSideControlInitialCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CellsSideControlSelectedSide.
        /// </summary>
        public static string CellsSideControlSelectedSide {
            get {
                return ResourceManager.GetString("CellsSideControlSelectedSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close procedure.
        /// </summary>
        public static string CloseProcedure {
            get {
                return ResourceManager.GetString("CloseProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Completed cicles:.
        /// </summary>
        public static string CompletedCicles {
            get {
                return ResourceManager.GetString("CompletedCicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm new resolution or cancel action..
        /// </summary>
        public static string ConfirmResolution {
            get {
                return ResourceManager.GetString("ConfirmResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Correct.
        /// </summary>
        public static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adjusted offset [mm]:.
        /// </summary>
        public static string CorrectOffset {
            get {
                return ResourceManager.GetString("CorrectOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cradle.
        /// </summary>
        public static string Cradle {
            get {
                return ResourceManager.GetString("Cradle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cradle Engine Selected.
        /// </summary>
        public static string CradleEngineSelected {
            get {
                return ResourceManager.GetString("CradleEngineSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current cell:.
        /// </summary>
        public static string CurrentCell {
            get {
                return ResourceManager.GetString("CurrentCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current height [mm]:.
        /// </summary>
        public static string CurrentHeight {
            get {
                return ResourceManager.GetString("CurrentHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current offset [mm]:.
        /// </summary>
        public static string CurrentOffset {
            get {
                return ResourceManager.GetString("CurrentOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current panel:.
        /// </summary>
        public static string CurrentPanel {
            get {
                return ResourceManager.GetString("CurrentPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current position [mm]:.
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current resolution [imp/mm]:.
        /// </summary>
        public static string CurrentResolution {
            get {
                return ResourceManager.GetString("CurrentResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delay between cicles [s]:.
        /// </summary>
        public static string DelayBetweenCicles {
            get {
                return ResourceManager.GetString("DelayBetweenCicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Initial position [mm]:.
        /// </summary>
        public static string DesiredInitialPosition {
            get {
                return ResourceManager.GetString("DesiredInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Desired movement [mm]:.
        /// </summary>
        public static string DesiredMovement {
            get {
                return ResourceManager.GetString("DesiredMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Correct Offset.
        /// </summary>
        public static string DoCorrectOffset {
            get {
                return ResourceManager.GetString("DoCorrectOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elevator Engine Selected.
        /// </summary>
        public static string ElevatorEngineSelected {
            get {
                return ResourceManager.GetString("ElevatorEngineSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Emergency End Run.
        /// </summary>
        public static string EmergencyEndRun {
            get {
                return ResourceManager.GetString("EmergencyEndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Feed rate:.
        /// </summary>
        public static string FeedRate {
            get {
                return ResourceManager.GetString("FeedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Front.
        /// </summary>
        public static string Front {
            get {
                return ResourceManager.GetString("Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate.
        /// </summary>
        public static string Gate {
            get {
                return ResourceManager.GetString("Gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Control 1.
        /// </summary>
        public static string Gate1Control {
            get {
                return ResourceManager.GetString("Gate1Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate 1.
        /// </summary>
        public static string Gate1Done {
            get {
                return ResourceManager.GetString("Gate1Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate 1 Height Control.
        /// </summary>
        public static string Gate1HeightControl {
            get {
                return ResourceManager.GetString("Gate1HeightControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate1 Height Reaced.
        /// </summary>
        public static string Gate1HeightReaced {
            get {
                return ResourceManager.GetString("Gate1HeightReaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Control 2.
        /// </summary>
        public static string Gate2Control {
            get {
                return ResourceManager.GetString("Gate2Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate 2.
        /// </summary>
        public static string Gate2Done {
            get {
                return ResourceManager.GetString("Gate2Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate 2 Height Control.
        /// </summary>
        public static string Gate2HeightControl {
            get {
                return ResourceManager.GetString("Gate2HeightControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Control 3.
        /// </summary>
        public static string Gate3Control {
            get {
                return ResourceManager.GetString("Gate3Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate 3.
        /// </summary>
        public static string Gate3Done {
            get {
                return ResourceManager.GetString("Gate3Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate 3 Height Control.
        /// </summary>
        public static string Gate3HeightControl {
            get {
                return ResourceManager.GetString("Gate3HeightControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate succesfully calibrated..
        /// </summary>
        public static string GateCalibrated {
            get {
                return ResourceManager.GetString("GateCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gates Control.
        /// </summary>
        public static string GateControl {
            get {
                return ResourceManager.GetString("GateControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate correction [mm]:.
        /// </summary>
        public static string GateCorrection {
            get {
                return ResourceManager.GetString("GateCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Height Control.
        /// </summary>
        public static string GateHeightControl {
            get {
                return ResourceManager.GetString("GateHeightControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate is out of tolerance..
        /// </summary>
        public static string GateOutOfTolerance {
            get {
                return ResourceManager.GetString("GateOutOfTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Sensor A.
        /// </summary>
        public static string GateSensorA {
            get {
                return ResourceManager.GetString("GateSensorA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate sensor A bay 1.
        /// </summary>
        public static string GateSensorABay1 {
            get {
                return ResourceManager.GetString("GateSensorABay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate sensor A bay 2.
        /// </summary>
        public static string GateSensorABay2 {
            get {
                return ResourceManager.GetString("GateSensorABay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate sensor A bay 3.
        /// </summary>
        public static string GateSensorABay3 {
            get {
                return ResourceManager.GetString("GateSensorABay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Sensor B.
        /// </summary>
        public static string GateSensorB {
            get {
                return ResourceManager.GetString("GateSensorB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate sensor B bay 1.
        /// </summary>
        public static string GateSensorBBay1 {
            get {
                return ResourceManager.GetString("GateSensorBBay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate sensor B bay 2.
        /// </summary>
        public static string GateSensorBBay2 {
            get {
                return ResourceManager.GetString("GateSensorBBay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate sensor B bay 3.
        /// </summary>
        public static string GateSensorBBay3 {
            get {
                return ResourceManager.GetString("GateSensorBBay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate Set Up.
        /// </summary>
        public static string GateSetUp {
            get {
                return ResourceManager.GetString("GateSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Go to cell.
        /// </summary>
        public static string GoToInitialPosition {
            get {
                return ResourceManager.GetString("GoToInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Height control bay 1.
        /// </summary>
        public static string HeightControlCheck1 {
            get {
                return ResourceManager.GetString("HeightControlCheck1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Height control bay 2.
        /// </summary>
        public static string HeightControlCheck2 {
            get {
                return ResourceManager.GetString("HeightControlCheck2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Height control bay 3.
        /// </summary>
        public static string HeightControlCheck3 {
            get {
                return ResourceManager.GetString("HeightControlCheck3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Horizontal axis homed.
        /// </summary>
        public static string HorizontalAxisHomedDone {
            get {
                return ResourceManager.GetString("HorizontalAxisHomedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Initial position:.
        /// </summary>
        public static string InitialPosition {
            get {
                return ResourceManager.GetString("InitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert desired movement..
        /// </summary>
        public static string InsertDesiredMovement {
            get {
                return ResourceManager.GetString("InsertDesiredMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserted weight [kg]:.
        /// </summary>
        public static string InsertedWeight {
            get {
                return ResourceManager.GetString("InsertedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert desired initial position..
        /// </summary>
        public static string InsertiDesiredInitialPosition {
            get {
                return ResourceManager.GetString("InsertiDesiredInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert mesured initial position..
        /// </summary>
        public static string InsertMesuredInitialPosition {
            get {
                return ResourceManager.GetString("InsertMesuredInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert mesured movement..
        /// </summary>
        public static string InsertMesuredMovement {
            get {
                return ResourceManager.GetString("InsertMesuredMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installation State.
        /// </summary>
        public static string InstallationState {
            get {
                return ResourceManager.GetString("InstallationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installer.
        /// </summary>
        public static string Installer {
            get {
                return ResourceManager.GetString("Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Laser gate 1.
        /// </summary>
        public static string Laser1Done {
            get {
                return ResourceManager.GetString("Laser1Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Laser gate 2.
        /// </summary>
        public static string Laser2Done {
            get {
                return ResourceManager.GetString("Laser2Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Laser gate 3.
        /// </summary>
        public static string Laser3Done {
            get {
                return ResourceManager.GetString("Laser3Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lower bound [mm]:.
        /// </summary>
        public static string LowerBound {
            get {
                return ResourceManager.GetString("LowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Low Speed Movements.
        /// </summary>
        public static string LowSpeedMovementsTest {
            get {
                return ResourceManager.GetString("LowSpeedMovementsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elevator.
        /// </summary>
        public static string LSMTElevator {
            get {
                return ResourceManager.GetString("LSMTElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate.
        /// </summary>
        public static string LSMTGateEngineButton {
            get {
                return ResourceManager.GetString("LSMTGateEngineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gate engine movements.
        /// </summary>
        public static string LSMTGateEngineTitle {
            get {
                return ResourceManager.GetString("LSMTGateEngineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Horizontal Axis.
        /// </summary>
        public static string LSMTHorizontalEngineButton {
            get {
                return ResourceManager.GetString("LSMTHorizontalEngineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Horizontal axis movements.
        /// </summary>
        public static string LSMTHorizontalEngineTitle {
            get {
                return ResourceManager.GetString("LSMTHorizontalEngineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical Axis.
        /// </summary>
        public static string LSMTVerticalEngineButton {
            get {
                return ResourceManager.GetString("LSMTVerticalEngineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical axis movements.
        /// </summary>
        public static string LSMTVerticalEngineTitle {
            get {
                return ResourceManager.GetString("LSMTVerticalEngineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LU Presence on Machine Cradle Side.
        /// </summary>
        public static string LuPresenceOnMachineCradleSide {
            get {
                return ResourceManager.GetString("LuPresenceOnMachineCradleSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LU Presence on Operator Cradle Side.
        /// </summary>
        public static string LuPresenceOnOperatorCradleSide {
            get {
                return ResourceManager.GetString("LuPresenceOnOperatorCradleSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LU Present in Bay 1.
        /// </summary>
        public static string LuPresentInBay {
            get {
                return ResourceManager.GetString("LuPresentInBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LU Present in Bay 2.
        /// </summary>
        public static string LuPresentInBay2 {
            get {
                return ResourceManager.GetString("LuPresentInBay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LU Present in Bay 3.
        /// </summary>
        public static string LuPresentInBay3 {
            get {
                return ResourceManager.GetString("LuPresentInBay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installation completed.
        /// </summary>
        public static string MachineDone {
            get {
                return ResourceManager.GetString("MachineDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manu.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Measured initial position [mm]:.
        /// </summary>
        public static string MesuredInitialPosition {
            get {
                return ResourceManager.GetString("MesuredInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mesured lenght [mm]:.
        /// </summary>
        public static string MesuredLenght {
            get {
                return ResourceManager.GetString("MesuredLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mesured movement [mm]:.
        /// </summary>
        public static string MesuredMovement {
            get {
                return ResourceManager.GetString("MesuredMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mesured weight [kg]:.
        /// </summary>
        public static string MesuredWeight {
            get {
                return ResourceManager.GetString("MesuredWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mesured weight is in tolerance..
        /// </summary>
        public static string MesuredWeightInTolerance {
            get {
                return ResourceManager.GetString("MesuredWeightInTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mesured weight is out of tolerance..
        /// </summary>
        public static string MesuredWeightOutOfTolerance {
            get {
                return ResourceManager.GetString("MesuredWeightOutOfTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Micro carter left side bay 1.
        /// </summary>
        public static string MicroCarterLeftSide {
            get {
                return ResourceManager.GetString("MicroCarterLeftSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Micro carter left side bay 2.
        /// </summary>
        public static string MicroCarterLeftSide2 {
            get {
                return ResourceManager.GetString("MicroCarterLeftSide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Micro carter left side bay 3.
        /// </summary>
        public static string MicroCarterLeftSide3 {
            get {
                return ResourceManager.GetString("MicroCarterLeftSide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Micro carter right side  bay 1.
        /// </summary>
        public static string MicroCarterRightSide {
            get {
                return ResourceManager.GetString("MicroCarterRightSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Micro carter right side bay 2.
        /// </summary>
        public static string MicroCarterRightSide2 {
            get {
                return ResourceManager.GetString("MicroCarterRightSide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Micro carter right side bay 3.
        /// </summary>
        public static string MicroCarterRightSide3 {
            get {
                return ResourceManager.GetString("MicroCarterRightSide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Middle.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Move to initial position..
        /// </summary>
        public static string MoveToInitialPosition {
            get {
                return ResourceManager.GetString("MoveToInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Move to position..
        /// </summary>
        public static string MoveToPosition {
            get {
                return ResourceManager.GetString("MoveToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Moving to desired position....
        /// </summary>
        public static string MovingToDesiredPosition {
            get {
                return ResourceManager.GetString("MovingToDesiredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mushroom Emergency Button bay 1.
        /// </summary>
        public static string MushroomHeadButton {
            get {
                return ResourceManager.GetString("MushroomHeadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mushroom Emergency Button bay 2.
        /// </summary>
        public static string MushroomHeadButton2 {
            get {
                return ResourceManager.GetString("MushroomHeadButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mushroom Emergency Button bay 3.
        /// </summary>
        public static string MushroomHeadButton3 {
            get {
                return ResourceManager.GetString("MushroomHeadButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New resolution [imp/mm]:.
        /// </summary>
        public static string NewResolution {
            get {
                return ResourceManager.GetString("NewResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Next &gt;  .
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nex panel.
        /// </summary>
        public static string NextPanel {
            get {
                return ResourceManager.GetString("NextPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offset [mm]:.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Offset Calibration.
        /// </summary>
        public static string OffsetCalibration {
            get {
                return ResourceManager.GetString("OffsetCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical axis origin.
        /// </summary>
        public static string OriginVerticalAxis {
            get {
                return ResourceManager.GetString("OriginVerticalAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Output:.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Panel correction [mm]:.
        /// </summary>
        public static string PanelCorrection {
            get {
                return ResourceManager.GetString("PanelCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Panels Control.
        /// </summary>
        public static string PanelsControl {
            get {
                return ResourceManager.GetString("PanelsControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Panels control procedure.
        /// </summary>
        public static string PanelsControlDescription {
            get {
                return ResourceManager.GetString("PanelsControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pawl Encoder.
        /// </summary>
        public static string PawlEncoder {
            get {
                return ResourceManager.GetString("PawlEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ReadFinalPosition.
        /// </summary>
        public static string ReadFinalPosition {
            get {
                return ResourceManager.GetString("ReadFinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ReadInitialPosition.
        /// </summary>
        public static string ReadInitialPosition {
            get {
                return ResourceManager.GetString("ReadInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reference&apos;s cell position [mm]:.
        /// </summary>
        public static string ReferenceCellHeight {
            get {
                return ResourceManager.GetString("ReferenceCellHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reference&apos;s cell number:.
        /// </summary>
        public static string ReferenceCellNumber {
            get {
                return ResourceManager.GetString("ReferenceCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reposition lenght [mm]:.
        /// </summary>
        public static string RepositionLenght {
            get {
                return ResourceManager.GetString("RepositionLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Final position.
        /// </summary>
        public static string RequestedFinalPosition {
            get {
                return ResourceManager.GetString("RequestedFinalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Required cicles:.
        /// </summary>
        public static string RequiredCicles {
            get {
                return ResourceManager.GetString("RequiredCicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset Security Function.
        /// </summary>
        public static string ResetSecurityFunction {
            get {
                return ResourceManager.GetString("ResetSecurityFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolution:.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolution Calibration.
        /// </summary>
        public static string ResolutionCalibration {
            get {
                return ResourceManager.GetString("ResolutionCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resolution correctly modified..
        /// </summary>
        public static string ResolutionModified {
            get {
                return ResourceManager.GetString("ResolutionModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Security Function Active.
        /// </summary>
        public static string SecurityFunctionActive {
            get {
                return ResourceManager.GetString("SecurityFunctionActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sensors&apos; State.
        /// </summary>
        public static string SensorsState {
            get {
                return ResourceManager.GetString("SensorsState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical axis origin set correctly..
        /// </summary>
        public static string SetOriginVerticalAxisCompleted {
            get {
                return ResourceManager.GetString("SetOriginVerticalAxisCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical axis origin not set..
        /// </summary>
        public static string SetOriginVerticalAxisNotCompleted {
            get {
                return ResourceManager.GetString("SetOriginVerticalAxisNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setting initial position....
        /// </summary>
        public static string SettingInitialPosition {
            get {
                return ResourceManager.GetString("SettingInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape gate 1.
        /// </summary>
        public static string Shape1Done {
            get {
                return ResourceManager.GetString("Shape1Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape gate 2.
        /// </summary>
        public static string Shape2Done {
            get {
                return ResourceManager.GetString("Shape2Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape gate 3.
        /// </summary>
        public static string Shape3Done {
            get {
                return ResourceManager.GetString("Shape3Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape Control.
        /// </summary>
        public static string ShapeControl {
            get {
                return ResourceManager.GetString("ShapeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Speed [mm/s]:.
        /// </summary>
        public static string SpeedMMSec {
            get {
                return ResourceManager.GetString("SpeedMMSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start procedure.
        /// </summary>
        public static string StartResolutionProcedure {
            get {
                return ResourceManager.GetString("StartResolutionProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Step -.
        /// </summary>
        public static string StepDown {
            get {
                return ResourceManager.GetString("StepDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Step +.
        /// </summary>
        public static string StepUp {
            get {
                return ResourceManager.GetString("StepUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Step value [mm]:.
        /// </summary>
        public static string StepValue {
            get {
                return ResourceManager.GetString("StepValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System error [mm]:.
        /// </summary>
        public static string SystemErrorMM {
            get {
                return ResourceManager.GetString("SystemErrorMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Test run:.
        /// </summary>
        public static string TestRun {
            get {
                return ResourceManager.GetString("TestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tolerance (+/-) [mm]:.
        /// </summary>
        public static string Tolerance {
            get {
                return ResourceManager.GetString("Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total panels:.
        /// </summary>
        public static string TotalPanels {
            get {
                return ResourceManager.GetString("TotalPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upper bound [mm]:.
        /// </summary>
        public static string UpperBound {
            get {
                return ResourceManager.GetString("UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Various Inputs.
        /// </summary>
        public static string VariousInputs {
            get {
                return ResourceManager.GetString("VariousInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify Circuit Integrity.
        /// </summary>
        public static string VerifyCircuitIntegrity {
            get {
                return ResourceManager.GetString("VerifyCircuitIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify Panel Position.
        /// </summary>
        public static string VerifyPanelPosition {
            get {
                return ResourceManager.GetString("VerifyPanelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verify Weight Controller.
        /// </summary>
        public static string VerifyWeightController {
            get {
                return ResourceManager.GetString("VerifyWeightController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical and craddle.
        /// </summary>
        public static string VerticalAxis {
            get {
                return ResourceManager.GetString("VerticalAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical Axis Brake.
        /// </summary>
        public static string VerticalAxisBrake {
            get {
                return ResourceManager.GetString("VerticalAxisBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a VerticalAxisButton.
        /// </summary>
        public static string VerticalAxisButton {
            get {
                return ResourceManager.GetString("VerticalAxisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calibrating verical axis....
        /// </summary>
        public static string VerticalAxisCalibrating {
            get {
                return ResourceManager.GetString("VerticalAxisCalibrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical Axis Calibration.
        /// </summary>
        public static string VerticalAxisCalibration {
            get {
                return ResourceManager.GetString("VerticalAxisCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical axis homed.
        /// </summary>
        public static string VerticalAxisHomedDone {
            get {
                return ResourceManager.GetString("VerticalAxisHomedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical Offset Calibration.
        /// </summary>
        public static string VerticalOffsetCalibration {
            get {
                return ResourceManager.GetString("VerticalOffsetCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical Offset Verified.
        /// </summary>
        public static string VerticalOffsetVerify {
            get {
                return ResourceManager.GetString("VerticalOffsetVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical Resolution Calibration.
        /// </summary>
        public static string VerticalResolutionCalibration {
            get {
                return ResourceManager.GetString("VerticalResolutionCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vertical resolution.
        /// </summary>
        public static string VerticalResolutionDone {
            get {
                return ResourceManager.GetString("VerticalResolutionDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Weight Control.
        /// </summary>
        public static string WeightControl {
            get {
                return ResourceManager.GetString("WeightControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zero Pawl Sensor.
        /// </summary>
        public static string ZeroPawlSensor {
            get {
                return ResourceManager.GetString("ZeroPawlSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zero Vertical Sensor.
        /// </summary>
        public static string ZeroVerticalSensor {
            get {
                return ResourceManager.GetString("ZeroVerticalSensor", resourceCulture);
            }
        }
    }
}
