//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.VW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperatorApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperatorApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.VW.Resources.OperatorApp", typeof(OperatorApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article description:.
        /// </summary>
        public static string ArticleDescription {
            get {
                return ResourceManager.GetString("ArticleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article:.
        /// </summary>
        public static string ArticleLable {
            get {
                return ResourceManager.GetString("ArticleLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Details.
        /// </summary>
        public static string ArticlesDetails {
            get {
                return ResourceManager.GetString("ArticlesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article state:.
        /// </summary>
        public static string ArticleState {
            get {
                return ResourceManager.GetString("ArticleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability [units]:.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch:.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string DescriptionLable {
            get {
                return ResourceManager.GetString("DescriptionLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatched quantity:.
        /// </summary>
        public static string DispatchedQuantity {
            get {
                return ResourceManager.GetString("DispatchedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string DrawerActivityConfirm {
            get {
                return ResourceManager.GetString("DrawerActivityConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List description:.
        /// </summary>
        public static string DrawerActivityDescrList {
            get {
                return ResourceManager.GetString("DrawerActivityDescrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DrawerActivityDetail {
            get {
                return ResourceManager.GetString("DrawerActivityDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking item detail:.
        /// </summary>
        public static string DrawerActivityDetailHeader {
            get {
                return ResourceManager.GetString("DrawerActivityDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot:.
        /// </summary>
        public static string DrawerActivityDetailLotto {
            get {
                return ResourceManager.GetString("DrawerActivityDetailLotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material status:.
        /// </summary>
        public static string DrawerActivityDetailMaterialStatus {
            get {
                return ResourceManager.GetString("DrawerActivityDetailMaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging type:.
        /// </summary>
        public static string DrawerActivityDetailPackagingType {
            get {
                return ResourceManager.GetString("DrawerActivityDetailPackagingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date:.
        /// </summary>
        public static string DrawerActivityDetailProductionDate {
            get {
                return ResourceManager.GetString("DrawerActivityDetailProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item code:.
        /// </summary>
        public static string DrawerActivityItem {
            get {
                return ResourceManager.GetString("DrawerActivityItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item description:.
        /// </summary>
        public static string DrawerActivityItemDescr {
            get {
                return ResourceManager.GetString("DrawerActivityItemDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List code:.
        /// </summary>
        public static string DrawerActivityList {
            get {
                return ResourceManager.GetString("DrawerActivityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking operations.
        /// </summary>
        public static string DrawerActivityPageHeader {
            get {
                return ResourceManager.GetString("DrawerActivityPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string DrawerActivityPosition {
            get {
                return ResourceManager.GetString("DrawerActivityPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock:.
        /// </summary>
        public static string DrawerActivityQtyCount {
            get {
                return ResourceManager.GetString("DrawerActivityQtyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked quantity:.
        /// </summary>
        public static string DrawerActivityQtyPick {
            get {
                return ResourceManager.GetString("DrawerActivityQtyPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested quantity:.
        /// </summary>
        public static string DrawerActivityQtyReq {
            get {
                return ResourceManager.GetString("DrawerActivityQtyReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List&apos;s row:.
        /// </summary>
        public static string DrawerActivityRowList {
            get {
                return ResourceManager.GetString("DrawerActivityRowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update max quantity.
        /// </summary>
        public static string DrawerActivityUpdateMaxQuantity {
            get {
                return ResourceManager.GetString("DrawerActivityUpdateMaxQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact front side.
        /// </summary>
        public static string DrawerCompactingAntCompact {
            get {
                return ResourceManager.GetString("DrawerCompactingAntCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragments quantity:.
        /// </summary>
        public static string DrawerCompactingFragmentNumber {
            get {
                return ResourceManager.GetString("DrawerCompactingFragmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compaction drawer procedure.
        /// </summary>
        public static string DrawerCompactingHeader {
            get {
                return ResourceManager.GetString("DrawerCompactingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max recoverable space:.
        /// </summary>
        public static string DrawerCompactingMaxSpaceRecoverable {
            get {
                return ResourceManager.GetString("DrawerCompactingMaxSpaceRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact back side.
        /// </summary>
        public static string DrawerCompactingRearCompact {
            get {
                return ResourceManager.GetString("DrawerCompactingRearCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side:.
        /// </summary>
        public static string DrawerCompactingSide {
            get {
                return ResourceManager.GetString("DrawerCompactingSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space to recover:.
        /// </summary>
        public static string DrawerCompactingSpaceToRecover {
            get {
                return ResourceManager.GetString("DrawerCompactingSpaceToRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string DrawerWaitNota {
            get {
                return ResourceManager.GetString("DrawerWaitNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled operations:.
        /// </summary>
        public static string DrawerWaitOperation {
            get {
                return ResourceManager.GetString("DrawerWaitOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for new drawer.
        /// </summary>
        public static string DrawerWaitPageHeader {
            get {
                return ResourceManager.GetString("DrawerWaitPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable Lists&apos; Rows.
        /// </summary>
        public static string ExecutableListsRows {
            get {
                return ResourceManager.GetString("ExecutableListsRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO Period:.
        /// </summary>
        public static string FIFOPeriod {
            get {
                return ResourceManager.GetString("FIFOPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General informations.
        /// </summary>
        public static string GeneralInfoHeader {
            get {
                return ResourceManager.GetString("GeneralInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation date:.
        /// </summary>
        public static string GeneralInfoInstallationDate {
            get {
                return ResourceManager.GetString("GeneralInfoInstallationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last maintenance date:.
        /// </summary>
        public static string GeneralInfoLastMaintenanceDate {
            get {
                return ResourceManager.GetString("GeneralInfoLastMaintenanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string GeneralInfoModel {
            get {
                return ResourceManager.GetString("GeneralInfoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next maintenance date:.
        /// </summary>
        public static string GeneralInfoNextMaintenanceDate {
            get {
                return ResourceManager.GetString("GeneralInfoNextMaintenanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operative machine&apos;s state:.
        /// </summary>
        public static string GeneralInfoOperativeStatus {
            get {
                return ResourceManager.GetString("GeneralInfoOperativeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number:.
        /// </summary>
        public static string GeneralInfoSerial {
            get {
                return ResourceManager.GetString("GeneralInfoSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released software version:.
        /// </summary>
        public static string GeneralInfoSwRelease {
            get {
                return ResourceManager.GetString("GeneralInfoSwRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer quantity:.
        /// </summary>
        public static string GeneralInfoTotDrawers {
            get {
                return ResourceManager.GetString("GeneralInfoTotDrawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer call.
        /// </summary>
        public static string ImmediateDrawerCallDrawerCall {
            get {
                return ResourceManager.GetString("ImmediateDrawerCallDrawerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate drawer call.
        /// </summary>
        public static string ImmediateDrawerCallHeader {
            get {
                return ResourceManager.GetString("ImmediateDrawerCallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested drawer:.
        /// </summary>
        public static string ImmediateDrawerCallRequiredDrawer {
            get {
                return ResourceManager.GetString("ImmediateDrawerCallRequiredDrawer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant Article.
        /// </summary>
        public static string InstantArticle {
            get {
                return ResourceManager.GetString("InstantArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item detail.
        /// </summary>
        public static string ItemDetailHeader {
            get {
                return ResourceManager.GetString("ItemDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing type:.
        /// </summary>
        public static string ItemDetailManagement {
            get {
                return ResourceManager.GetString("ItemDetailManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string ItemDetailNote {
            get {
                return ResourceManager.GetString("ItemDetailNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO period:.
        /// </summary>
        public static string ItemDetailPeriod {
            get {
                return ResourceManager.GetString("ItemDetailPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string ItemSearchBottom {
            get {
                return ResourceManager.GetString("ItemSearchBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item call.
        /// </summary>
        public static string ItemSearchCall {
            get {
                return ResourceManager.GetString("ItemSearchCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item detail.
        /// </summary>
        public static string ItemSearchDetail {
            get {
                return ResourceManager.GetString("ItemSearchDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string ItemSearchDown {
            get {
                return ResourceManager.GetString("ItemSearchDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search item by code or description.
        /// </summary>
        public static string ItemSearchHeader {
            get {
                return ResourceManager.GetString("ItemSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by code:.
        /// </summary>
        public static string ItemSearchKeySearch {
            get {
                return ResourceManager.GetString("ItemSearchKeySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available quantity:.
        /// </summary>
        public static string ItemSearchQtyAvailable {
            get {
                return ResourceManager.GetString("ItemSearchQtyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested quantity:.
        /// </summary>
        public static string ItemSearchQtyRequest {
            get {
                return ResourceManager.GetString("ItemSearchQtyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search item.
        /// </summary>
        public static string ItemSearchSearch {
            get {
                return ResourceManager.GetString("ItemSearchSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string ItemSearchTop {
            get {
                return ResourceManager.GetString("ItemSearchTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string ItemSearchUp {
            get {
                return ResourceManager.GetString("ItemSearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFO Period:.
        /// </summary>
        public static string LIFOPeriod {
            get {
                return ResourceManager.GetString("LIFOPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List description:.
        /// </summary>
        public static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List:.
        /// </summary>
        public static string ListLabel {
            get {
                return ResourceManager.GetString("ListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List detail.
        /// </summary>
        public static string ListsInWaitDetail {
            get {
                return ResourceManager.GetString("ListsInWaitDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string ListsInWaitDown {
            get {
                return ResourceManager.GetString("ListsInWaitDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute list.
        /// </summary>
        public static string ListsInWaitExecute {
            get {
                return ResourceManager.GetString("ListsInWaitExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for execution lists.
        /// </summary>
        public static string ListsInWaitHeader {
            get {
                return ResourceManager.GetString("ListsInWaitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string ListsInWaitNote {
            get {
                return ResourceManager.GetString("ListsInWaitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string ListsInWaitUp {
            get {
                return ResourceManager.GetString("ListsInWaitUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string Machines {
            get {
                return ResourceManager.GetString("Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management:.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawer operations.
        /// </summary>
        public static string NavigationMainMenuDrawerOperation {
            get {
                return ResourceManager.GetString("NavigationMainMenuDrawerOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search item.
        /// </summary>
        public static string NavigationMainMenuItems {
            get {
                return ResourceManager.GetString("NavigationMainMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting lists.
        /// </summary>
        public static string NavigationMainMenuLists {
            get {
                return ResourceManager.GetString("NavigationMainMenuLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string NavigationMainMenuOther {
            get {
                return ResourceManager.GetString("NavigationMainMenuOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compaction.
        /// </summary>
        public static string OtherNavigationCompaction {
            get {
                return ResourceManager.GetString("OtherNavigationCompaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Simulation.
        /// </summary>
        public static string OtherNavigationErrorSimulation {
            get {
                return ResourceManager.GetString("OtherNavigationErrorSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string OtherNavigationMaintenance {
            get {
                return ResourceManager.GetString("OtherNavigationMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string OtherNavigationStatistics {
            get {
                return ResourceManager.GetString("OtherNavigationStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging type:.
        /// </summary>
        public static string PackagingType {
            get {
                return ResourceManager.GetString("PackagingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking.
        /// </summary>
        public static string Picking {
            get {
                return ResourceManager.GetString("Picking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date:.
        /// </summary>
        public static string ProductionDate {
            get {
                return ResourceManager.GetString("ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested quantity:.
        /// </summary>
        public static string RequestedQuantity {
            get {
                return ResourceManager.GetString("RequestedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by code:.
        /// </summary>
        public static string SearchCode {
            get {
                return ResourceManager.GetString("SearchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a StatisticsGeneralDataHeader.
        /// </summary>
        public static string StatisticsGeneralDataHeader {
            get {
                return ResourceManager.GetString("StatisticsGeneralDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a StatisticsGeneralTestData.
        /// </summary>
        public static string StatisticsGeneralTestData {
            get {
                return ResourceManager.GetString("StatisticsGeneralTestData", resourceCulture);
            }
        }
    }
}
