resources:
- repo: self
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - Common
    - WMS
    - VerticalWarehouses\Panel PC UI

variables:
  BuildConfiguration: 'Debug'
  RestoreBuildProjects: 'VerticalWarehouses/Machine Automation Service/**/*.csproj'
  TestProjects: 'VerticalWarehouses/Machine Automation Service/**/*[Tt]ests/*.csproj'
  TargetFramework: 'netcoreapp2.1'


steps:

- task: DotNetCoreCLI@2
  displayName: 'NuGet restore'
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'
    feedsToUse: config
    nugetConfigPath: nuget.config


- template: ../../Pipelines/azure-pipeline-assembly-versioning-template.yml


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --framework $(TargetFramework)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(TestProjects)'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)  --framework $(TargetFramework) --no-build --no-restore'
    zipAfterPublish: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Machine Automation Service'
  inputs:
    PathtoPublish: 'VerticalWarehouses/Machine Automation Service/MAS_AutomationService/bin/$(BuildConfiguration)/$(TargetFramework)/publish'
    ArtifactName: 'automation_service'
