trigger:
- develop
- release
- master

pool:
  vmImage: 'windows-latest'

steps:
- template: azure-pipeline-vw-ui-template.yml
  parameters:
    BuildConfiguration: 'debug'
    BuildPlatform: 'any cpu'
