trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - 'VerticalWarehouses/Installer/*'
    - 'VerticalWarehouses/Simulator/*'
    - 'VerticalWarehouses/Machine Automation Service/*'
    - 'VerticalWarehouses/Panel PC UI/*'
    - 'Utility/Ferretto.VW.InvertersParametersGenerator/*'

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2'
  inputs:
    packageType: sdk
    version: 2.2.207
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.1'
  inputs:
    packageType: sdk
    version: 3.1.301
    installationPath: $(Agent.ToolsDirectory)/dotnet

- template: ../../Pipelines/azure-pipeline-assembly-versioning-template.yml

- script: dotnet publish "VerticalWarehouses/Utility/Ferretto.VW.TelemetryService/Ferretto.VW.TelemetryService.csproj" --runtime win10-x64 --configuration debug --self-contained --framework netcoreapp3.1
  displayName: 'Build & Publish (debug)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: telemetry_service'
  inputs:
    PathtoPublish: 'VerticalWarehouses/Utility/Ferretto.VW.TelemetryService/bin/debug/netcoreapp3.1/win10-x64/publish'
    ArtifactName: 'telemetry_service'

