resources:
- repo: self
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    exclude:
    - Common
    - WMS
    - VerticalWarehouses\Panel PC UI

steps:

- template: azure-pipeline-vw-services-template.yml
  parameters:
    BuildConfiguration: 'debug'
    RestoreBuildProjects: 'VerticalWarehouses/Machine Automation Service/**/*.csproj'
    TestProjects: 'VerticalWarehouses/Machine Automation Service/**/*[Tt]ests/*.csproj'
    TargetFramework: 'netcoreapp2.1'

