resources:
- repo: self
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - VerticalWarehouses\Simulator

steps:

- template: azure-pipeline-vw-simulator-template.yml
  parameters:
    BuildConfiguration: 'debug'
    BuildPlatform: 'any cpu'
