trigger:
  batch: true
  branches:
    include:
    - develop
    - release
    - master
  paths:
    include:
    - VerticalWarehouses/Installer/*

pool:
  vmImage: 'windows-latest'

steps:
- template: azure-pipeline-vw-installer-template.yml
  parameters:                
    RestoreBuildProjects: '**/Ferretto.VW.Installer.csproj'    
    
