resources:
- repo: self
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - VerticalWarehouses\Common
    - VerticalWarehouses\Machine Automation Service

steps:

- template: azure-pipeline-vw-services-template.yml
  parameters:
    BuildConfiguration: 'debug'
    RestoreBuildProjects: '**/Ferretto.VW.MAS.AutomationService.csproj'
    TestProjects: 'VerticalWarehouses/Machine Automation Service/**/*.Tests.csproj'
    TargetFramework: 'netcoreapp2.2'
