trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - VerticalWarehouses/Installer/*

pool:
  vmImage: 'windows-latest'

steps:

- template: azure-pipeline-vw-simulator-template.yml
  parameters:
    BuildConfiguration: 'debug'
    BuildPlatform: 'any cpu'
