trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    exclude:
    - VerticalWarehouses/Installer/*
    - VerticalWarehouses/Simulator/*

pool:
  vmImage: 'windows-latest'

steps:
- template: azure-pipeline-vw-ui-template.yml
  parameters:
    BuildConfiguration: 'debug'
    BuildPlatform: 'any cpu'
