trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - 'VerticalWarehouses/Utility/*'
    - 'VerticalWarehouses/Machine Automation Service/Ferretto.VW.MAS.DataModels/*'

pool:
  vmImage: 'windows-latest'

steps:
- template: azure-pipeline-vw-inverter-utility-template.yml    
    
