delete from BarcodeActions

DBCC CHECKIDENT( 'BarcodeActions', RESEED, 0)

INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('FilterItems', 'ItemsSearch', '^(?<ItemCode>[0-9A-Za-z_\.\/ \-\+\|]+)', 1, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('PickItem', 'ItemsSearch', '^ITEM_(?<ItemCode>[0-9A-Za-z]+)_QTY(?<ItemQuantity>[0-9]+)_PICK', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('FilterLists', 'ListSearch', '^LIST_(?<ListId>[0-9]+)_FILTER', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('ExecuteList', 'ListSearch', '^(?<ListId>[0-9A-Za-z_\.\/ \-\+\|]+)', 1, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('LoginUser', 'Login', '^(?<BearerToken>[a-zA-Z0-9_\.\/ \-\+]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('RecallLoadingUnit', NULL, '^\$RIENTROUDC', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemPick', '^(?<ItemCode>[a-zA-Z0-9_\.\/ \-\+\|]+)', 2, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('ConfirmOperation', 'ItemPick', '^#CONFIRM#(QTY_(?<ItemQuantity>[0-9]+))?', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemPut', '^(?<ItemCode>[0-9a-zA-Z_\.\/ \-\+\|]+)', 2, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemInventory', '^(?<ItemCode>[0-9a-zA-Z_\.\/ \-\+\|]+)', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('SelectBasket', NULL, '^#BASKET(?<BasketCode>[0-9a-zA-Z]+)', 10, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('SelectShelf', NULL, '^@(?<ShelfCode>[0-9a-zA-Z]+)', 0, 11, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('AssociateBasketToShelf', NULL, '^\$APERTURACOLLO', 10, 12, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('CompleteBasket', NULL, '^\$CHIUSURACOLLO', 10, 12, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('RemoveFullBasket', NULL, '^\$SATURAZIONECOLLO', 10, 12, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('SelectMachine', NULL, '^\$MAC(?<MachineCode>[0-9a-zA-Z]+)', 10, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('SelectCar', NULL, '^\$NUMEROCARRELLO(?<CarCode>[0-9a-zA-Z]+)', 0, 16, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('CarToMachine', NULL, '^\$APERTURACARRELLO', 10, 17, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('CarComplete', NULL, '^\$CHIUSURACARRELLO', 10, 17, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('Notes', 'NoteDescription', '^(?<ItemCode>[0-9A-Za-z_\.\/ \-\+\|]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('ConfirmKey', 'ItemPick', '^\$CONFIRM', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('ConfirmKey', 'ItemPut', '^\$CONFIRM', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('ConfirmKey', 'ItemInventory', '^\$CONFIRM', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemPick', '^(?<ItemLot>[0-9]{999})$', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemPick', '^(?<ItemSerialNumber>[0-9]{999})$', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemPut', '^(?<ItemLot>[0-9]{999})$', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions (action,contextName,pattern, priority, nextRuleId, restartOnMismatch) VALUES ('VerifyItem', 'ItemPut', '^(?<ItemSerialNumber>[0-9]{999})$', 1, NULL, 'TRUE')
