delete from BarcodeActions

DBCC CHECKIDENT( 'BarcodeActions', RESEED, 0)

INSERT INTO BarcodeActions VALUES ('FilterItems', 'ItemsSearch', '^(?<ItemCode>[0-9A-Za-z_\.\/ \-\+\|]+)', 1, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('PickItem', 'ItemsSearch', '^ITEM_(?<ItemCode>[0-9A-Za-z]+)_QTY(?<ItemQuantity>[0-9]+)_PICK', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('FilterLists', 'ListSearch', '^LIST_(?<ListId>[0-9]+)_FILTER', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('ExecuteList', 'ListSearch', '^(?<ListId>[0-9A-Za-z_\.\/ \-\+\|]+)', 1, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('LoginUser', 'Login', '^(?<BearerToken>[a-zA-Z0-9_\.\/ \-\+]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('RecallLoadingUnit', NULL, '^\$RIENTROUDC', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('VerifyItem', 'ItemPick', '^(?<ItemCode>[a-zA-Z0-9_\.\/ \-\+\|]+)', 2, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('ConfirmOperation', 'ItemPick', '^#CONFIRM#(QTY_(?<ItemQuantity>[0-9]+))?', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('VerifyItem', 'ItemPut', '^(?<ItemCode>[0-9a-zA-Z_\.\/ \-\+\|]+)', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('VerifyItem', 'ItemInventory', '^(?<ItemCode>[0-9a-zA-Z_\.\/ \-\+\|]+)', 1, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('SelectBasket', NULL, '^#BASKET(?<BasketCode>[0-9a-zA-Z]+)', 10, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('SelectShelf', NULL, '^#SHELF(?<ShelfCode>[0-9a-zA-Z]+)', 0, 11, 'TRUE')
INSERT INTO BarcodeActions VALUES ('AssociateBasketToShelf', NULL, '^\$APRICOLLO', 10, 12, 'TRUE')
INSERT INTO BarcodeActions VALUES ('CompleteBasket', NULL, '^\$CHIUDICOLLO', 10, 12, 'TRUE')
INSERT INTO BarcodeActions VALUES ('RemoveFullBasket', NULL, '^\$COLLOPIENO', 10, 12, 'TRUE')
INSERT INTO BarcodeActions VALUES ('SelectMachine', NULL, '^$MAC(?<MachineCode>[0-9a-zA-Z]+)', 10, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('SelectCar', NULL, '^\$CARRELLO(?<CarCode>[0-9a-zA-Z]+)', 0, 15, 'TRUE')
INSERT INTO BarcodeActions VALUES ('CarToMachine', NULL, '^\$APERTURACARRELLO', 10, 16, 'TRUE')
INSERT INTO BarcodeActions VALUES ('Notes', 'NoteDescription', '^(?<ItemCode>[0-9A-Za-z_\.\/ \-\+\|]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('ConfirmKey', 'ItemPick', '^\$CONFIRM', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('ConfirmKey', 'ItemPut', '^\$CONFIRM', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('ConfirmKey', 'ItemInventory', '^\$CONFIRM', 0, NULL, 'FALSE')
