delete from BarcodeActions

DBCC CHECKIDENT( 'BarcodeActions', RESEED, 0)

INSERT INTO BarcodeActions VALUES ('FilterItems', 'ItemsSearch', '(?<ItemCode>[0-9A-Za-z_\.\/ ]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('PickItem', 'ItemsSearch', 'ITEM_(?<ItemCode>[0-9A-Za-z]+)_QTY(?<ItemQuantity>[0-9]+)_PICK', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('FilterLists', 'ListSearch', 'LIST_(?<ListId>[0-9]+)_FILTER', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('ExecuteList', 'ListSearch', '(?<ListId>[0-9A-Za-z_\.\/ ]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('LoginUser', 'Login', '(?<BearerToken>[a-zA-Z0-9_\.\/ ]+)', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('RecallLoadingUnit', NULL, '\$RIENTROUDC', 0, NULL, 'FALSE')
INSERT INTO BarcodeActions VALUES ('VerifyItem', 'ItemPick', '(?<ItemCode>[a-zA-Z0-9_\.\/ ]+)', 0, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('ConfirmOperation', 'ItemPick', '#CONFIRM#(QTY_(?<ItemQuantity>[0-9]+))?', 0, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('VerifyItem', 'ItemPut', '(?<ItemCode>[0-9a-zA-Z_\.\/ ]+)', 0, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('VerifyItem', 'ItemInventory', '(?<ItemCode>[0-9a-zA-Z_\.\/ ]+)', 0, NULL, 'TRUE')
INSERT INTO BarcodeActions VALUES ('SelectBasket', NULL, '#BASKET(?<BasketCode>[0-9a-zA-Z]+)', 1000, 12, 'TRUE')
INSERT INTO BarcodeActions VALUES ('SelectShelf', NULL, '#SHELF(?<ShelfCode>[0-9a-zA-Z]+)', 0, 1000, 'TRUE')
INSERT INTO BarcodeActions VALUES ('AssociateBasketToShelf', NULL, '\$APERTURACOLLO', 10, 11, 'TRUE')
INSERT INTO BarcodeActions VALUES ('CompleteBasket', NULL, '\$CHIUSURACOLLO', 10, 11, 'TRUE')
INSERT INTO BarcodeActions VALUES ('RemoveFullBasket', NULL, '\$SATURAZIONECAMPATA', 10, 11, 'TRUE')
INSERT INTO BarcodeActions VALUES ('Notes', 'NoteDescription', '(?<ItemCode>[0-9A-Za-z_\.\/ ]+)', 0, NULL, 'FALSE')
