resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - master
    - release/*
    - bugfix/*
    - hotfix/*

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'debug'

steps:


- template: azure-pipeline-net4-nuget-template.yml


- template: azure-pipeline-assembly-versioning-template.yml


- task: VSBuild@1
  displayName: 'Build solution WMS.App'
  inputs:
    solution: 'WMS\WMS.App.sln'
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
    msbuildArchitecture: x64


