resources:
- repo: self
  clean: true

queue:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

trigger:
  branches:
    include:
    - master
    - release/*
    - bugfix/*
    - hotfix/*
  paths:
    exclude:
    - VerticalWarehouses

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:

- task: CopyFiles@2
  displayName: 'Copy sources to staging directory'
  inputs:
    Contents: |
     **
     !**\.git\**
     !**\*.png
     !**\*.jpg
    targetFolder: '$(Build.ArtifactStagingDirectory)\sources'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Common Sources'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\sources'
    ArtifactName: 'common_sources'


- template: azure-pipeline-net4-nuget-template.yml

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Common Sources'
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'common_sources'


- template: azure-pipeline-assembly-versioning-template.yml


- task: VSBuild@1
  displayName: 'Build solution WMS.App'
  inputs:
    solution: WMS.App.sln
    msbuildArgs: '-v:normal'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64


- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'


- task: CopyFiles@2
  displayName: 'Copy Files to staging directory'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- template: azure-pipeline-publish-artifacts-template.yml

