resources:
- repo: self
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - '*'
    - 'VerticalWarehouses\Machine Automation Service'
    exclude:
    - Common
    - WMS
    - VerticalWarehouses

variables:
  BuildConfiguration: 'Debug'
  RestoreBuildProjects: 'VerticalWarehouses/Machine Automation Service/**/*.csproj'
  TestProjects: 'VerticalWarehouses/Machine Automation Service/**/*[Tt]ests/*.csproj'
  TargetFramework: 'netcoreapp2.1'


steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(RestoreBuildProjects)'
    feedsToUse: config
    nugetConfigPath: nuget.config


# TODO: uncomment this template when this bug is solved: https://github.com/GitTools/GitVersion/issues/1483
# - template: azure-pipeline-assembly-versioning-template.yml


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) --framework $(TargetFramework)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)  --framework $(TargetFramework) --no-build --no-restore'
    zipAfterPublish: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: 'VerticalWarehouses/Machine Automation Service'
    ArtifactName: 'automation_services'


