resources:
- repo: self
  fetchDepth: 15
queue:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - '*'
    - 'VerticalWarehouses\Panel PC User Interface'
    exclude:
    - Common
    - WMS
    - VerticalWarehouses

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  TargetSolution: 'VerticalWarehouses\VerticalWarehouses.sln'


steps:

- template: azure-pipeline-net4-nuget-template.yml


- template: azure-pipeline-assembly-versioning-template.yml


- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(TargetSolution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'


- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'


- task: PublishSymbols@2
  displayName: 'Publish symbols path'
  inputs:
    SearchPattern: '**\bin\**\*.pdb'
    PublishSymbols: false
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'


