resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - master
    - release/*
    - bugfix/*
    - hotfix/*

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

steps:

- template: '../WMS/Pipelines/azure-pipeline-wms-services-template.yml'
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    TargetFramework: 'netcoreapp2.2'
    RestoreBuildProjects: 'WMS/Data/**/*.csproj'
    TestProjects: 'WMS/Data/**/*.Tests.csproj'

    
- template: ../WMS/Pipelines/azure-pipeline-wms-ui-template.yml
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    BuildPlatform:  $(BuildPlatform)

   
- template: '../VerticalWarehouses/Pipelines/azure-pipeline-vw-services-template.yml'
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    TargetFramework: 'netcoreapp2.1'
    RestoreBuildProjects: 'VerticalWarehouses/Machine Automation Service/**/*.csproj'
    TestProjects: 'VerticalWarehouses/Machine Automation Service/**/*Tests/*.csproj'


- template: '../VerticalWarehouses/Pipelines/azure-pipeline-vw-ui-template.yml'
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    BuildPlatform:  $(BuildPlatform)

