resources:
- repo: self
  clean: true
  fetchDepth: 15

queue:
  name: Hosted VS2017
  demands:
    - msbuild
    - visualstudio
    - vstest

trigger:
  branches:
    include:
    - master
    - release/*
    - bugfix/*
    - hotfix/*

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'
  TargetFramework: 'netcoreapp2.1'

steps:

- template: ../WMS/Pipelines/azure-pipeline-wms-services-template.yml
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    TargetFramework: $(TargetFramework)
    RestoreBuildProjects: 'WMS/Data/**/*.csproj'
    TestProjects: 'WMS/Data/**/*.Tests.csproj'

- template: ../WMS/Pipelines/azure-pipeline-wms-ui-template.yml
  parameters:
    BuildConfiguration: $(BuildConfiguration)
    BuildPlatform:  $(BuildPlatform)

- template: azure-pipeline-net4-nuget-template.yml




- task: VSBuild@1
  displayName: 'Build VerticalWarehouses'
  inputs:
    solution: 'VerticalWarehouses\VerticalWarehouses.sln'
    msbuildArgs: '-v:normal'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64


- task: DotNetCoreCLI@2
  displayName: 'Build Machine Automation Service'
  inputs:
    projects: 'VerticalWarehouses/Machine Automation Service/**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --framework $(TargetFramework)'


- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\**\*tests.dll
     !**\obj\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'


- task: CopyFiles@2
  displayName: 'Copy Files to staging directory'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Desktop App'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/WMS/App/App/bin/$(BuildConfiguration)/net471'
    ArtifactName: 'desktop_app'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Panel Pc App'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/VerticalWarehouses/Panel PC UI/VWApp/bin/$(BuildConfiguration)/net471'
    ArtifactName: 'panelpc_app'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Machine Automation Service'
  inputs:
    PathtoPublish: 'VerticalWarehouses/Machine Automation Service/MAS_AutomationService/bin/$(BuildConfiguration)/$(TargetFramework)/publish'
    ArtifactName: 'automation_service'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: on_premises_appconfig_transform'
  inputs:
    PathtoPublish: 'WMS/App/App'
    ArtifactName: 'on_premises_appconfig_transform'

