resources:
- repo: self
  fetchDepth: 15

queue:
  name: Hosted Ubuntu 1604

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - Common\Resources
    exclude:
    - Common
    - WMS


variables:
  BuildConfiguration: 'Release'
  RestoreBuildProjects: 'VerticalWarehouses/Machine Automation Service/**/*.csproj'
  TestProjects: 'VerticalWarehouses/Machine Automation Service/**/*[Tt]ests/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

    projects: '$(Parameters.RestoreBuildProjects)'

    feedsToUse: config

    nugetConfigPath: nuget.config


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'

    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test

    projects: '$(Parameters.TestProjects)'

    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish

    publishWebProjects: True

    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    zipAfterPublish: True


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

    ArtifactName: 'automation_services'


