//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.VW.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.VW.App.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area of the machine is unknown.
        /// </summary>
        public static string AreaMachineUnknow {
            get {
                return ResourceManager.GetString("AreaMachineUnknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test in progress... Unable to exit the page.
        /// </summary>
        public static string BackShutterTest {
            get {
                return ResourceManager.GetString("BackShutterTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS error: Bad Request..
        /// </summary>
        public static string BadRequestTitle {
            get {
                return ResourceManager.GetString("BadRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bay.
        /// </summary>
        public static string Bay {
            get {
                return ResourceManager.GetString("Bay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bay.
        /// </summary>
        public static string BayNumber {
            get {
                return ResourceManager.GetString("BayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string BayOneName {
            get {
                return ResourceManager.GetString("BayOneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string BayThreeName {
            get {
                return ResourceManager.GetString("BayThreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string BayTwoName {
            get {
                return ResourceManager.GetString("BayTwoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme change.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to automatic mode the machine and restore all pending movements?.
        /// </summary>
        public static string ConfirmMachineModeSwitchAutomatic {
            get {
                return ResourceManager.GetString("ConfirmMachineModeSwitchAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to power up the machine?.
        /// </summary>
        public static string ConfirmMachineRun {
            get {
                return ResourceManager.GetString("ConfirmMachineRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity.
        /// </summary>
        public static string Connectivity {
            get {
                return ResourceManager.GetString("Connectivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter can only convert to value of type Visibility..
        /// </summary>
        public static string ConverterCanConvertOnlyToVisibilityType {
            get {
                return ResourceManager.GetString("ConverterCanConvertOnlyToVisibilityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy.MM.dd HH:mm}.
        /// </summary>
        public static string DateFormatComplete {
            get {
                return ResourceManager.GetString("DateFormatComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0: yyyy.MM.dd}.
        /// </summary>
        public static string DateFormatDayNumber {
            get {
                return ResourceManager.GetString("DateFormatDayNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} days ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEBUG.
        /// </summary>
        public static string DiagnosticDetailTitle {
            get {
                return ResourceManager.GetString("DiagnosticDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error communicating with services..
        /// </summary>
        public static string ErrorCommunicatingWithServices {
            get {
                return ResourceManager.GetString("ErrorCommunicatingWithServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finite state machine.
        /// </summary>
        public static string FiniteMachineState {
            get {
                return ResourceManager.GetString("FiniteMachineState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden operation.
        /// </summary>
        public static string ForbiddenOperation {
            get {
                return ResourceManager.GetString("ForbiddenOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id loading unit does not exists..
        /// </summary>
        public static string IdLoadingUnitNotExists {
            get {
                return ResourceManager.GetString("IdLoadingUnitNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter.
        /// </summary>
        public static string Inverter {
            get {
                return ResourceManager.GetString("Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Drive.
        /// </summary>
        public static string IODrive {
            get {
                return ResourceManager.GetString("IODrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property of the &apos;{1}&apos; view model shall contain a valid loading unit identifier..
        /// </summary>
        public static string LoadingUnitViewModelPropertyIdentifier {
            get {
                return ResourceManager.GetString("LoadingUnitViewModelPropertyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the lot of this product.
        /// </summary>
        public static string LotManagedProduct {
            get {
                return ResourceManager.GetString("LotManagedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string MachineRun {
            get {
                return ResourceManager.GetString("MachineRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string ManualMode {
            get {
                return ResourceManager.GetString("ManualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax for NameOf is Type={x:Type className&gt;}.&lt;.
        /// </summary>
        public static string MarkupNameOfSyntax {
            get {
                return ResourceManager.GetString("MarkupNameOfSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No row in the list.
        /// </summary>
        public static string NoRows {
            get {
                return ResourceManager.GetString("NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not present.
        /// </summary>
        public static string NotPresent {
            get {
                return ResourceManager.GetString("NotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter cannot be null or empty..
        /// </summary>
        public static string ParameterCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number:.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down ....
        /// </summary>
        public static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Socket Link.
        /// </summary>
        public static string SocketLinkEnabled {
            get {
                return ResourceManager.GetString("SocketLinkEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of line LF.
        /// </summary>
        public static string SocketLinkEndOfLine {
            get {
                return ResourceManager.GetString("SocketLinkEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling interval.
        /// </summary>
        public static string SocketLinkPolling {
            get {
                return ResourceManager.GetString("SocketLinkPolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SocketLinkPort {
            get {
                return ResourceManager.GetString("SocketLinkPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SocketLinkTimeout {
            get {
                return ResourceManager.GetString("SocketLinkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string StatusDebug {
            get {
                return ResourceManager.GetString("StatusDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Off.
        /// </summary>
        public static string SwitchOff {
            get {
                return ResourceManager.GetString("SwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Automatic.
        /// </summary>
        public static string SwitchToAutomatic {
            get {
                return ResourceManager.GetString("SwitchToAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Manual.
        /// </summary>
        public static string SwitchToManual {
            get {
                return ResourceManager.GetString("SwitchToManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string TargetNullValue {
            get {
                return ResourceManager.GetString("TargetNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (ms).
        /// </summary>
        public static string TimeoutMs {
            get {
                return ResourceManager.GetString("TimeoutMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token status.
        /// </summary>
        public static string TokenStatus {
            get {
                return ResourceManager.GetString("TokenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string WarehouseSide_Back {
            get {
                return ResourceManager.GetString("WarehouseSide_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string WarehouseSide_Front {
            get {
                return ResourceManager.GetString("WarehouseSide_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string WmsDisabled {
            get {
                return ResourceManager.GetString("WmsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled WMS.
        /// </summary>
        public static string WmsEnabled {
            get {
                return ResourceManager.GetString("WmsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
