//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.VW.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.VW.App.Resources.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration management and Laser functionality test.
        /// </summary>
        public static string AccessoriesMenuDescription {
            get {
                return ResourceManager.GetString("AccessoriesMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories Menu.
        /// </summary>
        public static string AccessoriesMenuName {
            get {
                return ResourceManager.GetString("AccessoriesMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Pointer.
        /// </summary>
        public static string AccessoriesMenuTitle {
            get {
                return ResourceManager.GetString("AccessoriesMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Status.
        /// </summary>
        public static string InstallationStatus {
            get {
                return ResourceManager.GetString("InstallationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string MenuAccessories {
            get {
                return ResourceManager.GetString("MenuAccessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bays.
        /// </summary>
        public static string MenuBays {
            get {
                return ResourceManager.GetString("MenuBays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string MenuCells {
            get {
                return ResourceManager.GetString("MenuCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevator.
        /// </summary>
        public static string MenuElevator {
            get {
                return ResourceManager.GetString("MenuElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Units.
        /// </summary>
        public static string MenuLoadingUnits {
            get {
                return ResourceManager.GetString("MenuLoadingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements.
        /// </summary>
        public static string Movements {
            get {
                return ResourceManager.GetString("Movements", resourceCulture);
            }
        }
    }
}
