//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.Common.Resources.BusinessObjects", typeof(BusinessObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Class.
        /// </summary>
        public static string AbcClass {
            get {
                return ResourceManager.GetString("AbcClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aisle.
        /// </summary>
        public static string Aisle {
            get {
                return ResourceManager.GetString("Aisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Capacity.
        /// </summary>
        public static string AllowedItemInCompartmentMaxCapacity {
            get {
                return ResourceManager.GetString("AllowedItemInCompartmentMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string AreaDescription {
            get {
                return ResourceManager.GetString("AreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BayDescription {
            get {
                return ResourceManager.GetString("BayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Units Buffer Size.
        /// </summary>
        public static string BayLoadingUnitsBufferSize {
            get {
                return ResourceManager.GetString("BayLoadingUnitsBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bay Type.
        /// </summary>
        public static string BayType {
            get {
                return ResourceManager.GetString("BayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string CellColumn {
            get {
                return ResourceManager.GetString("CellColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Column.
        /// </summary>
        public static string CellColumn_extended {
            get {
                return ResourceManager.GetString("CellColumn_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string CellFloor {
            get {
                return ResourceManager.GetString("CellFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Floor.
        /// </summary>
        public static string CellFloor_extended {
            get {
                return ResourceManager.GetString("CellFloor_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Units Count.
        /// </summary>
        public static string CellLoadingUnitsCount {
            get {
                return ResourceManager.GetString("CellLoadingUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Units Description.
        /// </summary>
        public static string CellLoadingUnitsDescription {
            get {
                return ResourceManager.GetString("CellLoadingUnitsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string CellNumber {
            get {
                return ResourceManager.GetString("CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number.
        /// </summary>
        public static string CellNumber_extended {
            get {
                return ResourceManager.GetString("CellNumber_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Position.
        /// </summary>
        public static string CellPosition {
            get {
                return ResourceManager.GetString("CellPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Position Description.
        /// </summary>
        public static string CellPositionDescription {
            get {
                return ResourceManager.GetString("CellPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string CellPriority {
            get {
                return ResourceManager.GetString("CellPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string CellSide {
            get {
                return ResourceManager.GetString("CellSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Side.
        /// </summary>
        public static string CellSide_extended {
            get {
                return ResourceManager.GetString("CellSide_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CellStatus {
            get {
                return ResourceManager.GetString("CellStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string CellType {
            get {
                return ResourceManager.GetString("CellType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Coordinate.
        /// </summary>
        public static string CellXCoordinate {
            get {
                return ResourceManager.GetString("CellXCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Coordinate.
        /// </summary>
        public static string CellYCoordinate {
            get {
                return ResourceManager.GetString("CellYCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Coordinate.
        /// </summary>
        public static string CellZCoordinate {
            get {
                return ResourceManager.GetString("CellZCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CompartmentCode {
            get {
                return ResourceManager.GetString("CompartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO Time.
        /// </summary>
        public static string CompartmentFifoTime {
            get {
                return ResourceManager.GetString("CompartmentFifoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Store Date.
        /// </summary>
        public static string CompartmentFirstStoreDate {
            get {
                return ResourceManager.GetString("CompartmentFirstStoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string CompartmentHeight {
            get {
                return ResourceManager.GetString("CompartmentHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Handling Date.
        /// </summary>
        public static string CompartmentLastHandlingDate {
            get {
                return ResourceManager.GetString("CompartmentLastHandlingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inventory Date.
        /// </summary>
        public static string CompartmentLastInventoryDate {
            get {
                return ResourceManager.GetString("CompartmentLastInventoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Pick Date.
        /// </summary>
        public static string CompartmentLastPickDate {
            get {
                return ResourceManager.GetString("CompartmentLastPickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Store Date.
        /// </summary>
        public static string CompartmentLastStoreDate {
            get {
                return ResourceManager.GetString("CompartmentLastStoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string CompartmentLot {
            get {
                return ResourceManager.GetString("CompartmentLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Capacity.
        /// </summary>
        public static string CompartmentMaxCapacity {
            get {
                return ResourceManager.GetString("CompartmentMaxCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing.
        /// </summary>
        public static string CompartmentPairing {
            get {
                return ResourceManager.GetString("CompartmentPairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for Pick.
        /// </summary>
        public static string CompartmentReservedForPick {
            get {
                return ResourceManager.GetString("CompartmentReservedForPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved to Store.
        /// </summary>
        public static string CompartmentReservedToStore {
            get {
                return ResourceManager.GetString("CompartmentReservedToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Status.
        /// </summary>
        public static string CompartmentStatus {
            get {
                return ResourceManager.GetString("CompartmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string CompartmentStock {
            get {
                return ResourceManager.GetString("CompartmentStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub 1.
        /// </summary>
        public static string CompartmentSub1 {
            get {
                return ResourceManager.GetString("CompartmentSub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub 2.
        /// </summary>
        public static string CompartmentSub2 {
            get {
                return ResourceManager.GetString("CompartmentSub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Type.
        /// </summary>
        public static string CompartmentType {
            get {
                return ResourceManager.GetString("CompartmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Type Description.
        /// </summary>
        public static string CompartmentTypeDescription {
            get {
                return ResourceManager.GetString("CompartmentTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string CompartmentWidth {
            get {
                return ResourceManager.GetString("CompartmentWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Position.
        /// </summary>
        public static string CompartmentXPosition {
            get {
                return ResourceManager.GetString("CompartmentXPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Position.
        /// </summary>
        public static string CompartmentYPosition {
            get {
                return ResourceManager.GetString("CompartmentYPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string ItemAvailable {
            get {
                return ResourceManager.GetString("ItemAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Weight.
        /// </summary>
        public static string ItemAverageWeight {
            get {
                return ResourceManager.GetString("ItemAverageWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ItemCategory {
            get {
                return ResourceManager.GetString("ItemCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ItemClass {
            get {
                return ResourceManager.GetString("ItemClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ItemCode {
            get {
                return ResourceManager.GetString("ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string ItemCode_extended {
            get {
                return ResourceManager.GetString("ItemCode_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string ItemDescription_extended {
            get {
                return ResourceManager.GetString("ItemDescription_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO Pick Time.
        /// </summary>
        public static string ItemFifoPickTime {
            get {
                return ResourceManager.GetString("ItemFifoPickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO Store Time.
        /// </summary>
        public static string ItemFifoStoreTime {
            get {
                return ResourceManager.GetString("ItemFifoStoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ItemHeight {
            get {
                return ResourceManager.GetString("ItemHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Tolerance.
        /// </summary>
        public static string ItemInventoryTolerance {
            get {
                return ResourceManager.GetString("ItemInventoryTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Inventory Date.
        /// </summary>
        public static string ItemLastInventoryDate {
            get {
                return ResourceManager.GetString("ItemLastInventoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Pick Date.
        /// </summary>
        public static string ItemLastPickDate {
            get {
                return ResourceManager.GetString("ItemLastPickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Store Date.
        /// </summary>
        public static string ItemLastStoreDate {
            get {
                return ResourceManager.GetString("ItemLastStoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string ItemLength {
            get {
                return ResourceManager.GetString("ItemLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Type.
        /// </summary>
        public static string ItemManagementType {
            get {
                return ResourceManager.GetString("ItemManagementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ItemNotes {
            get {
                return ResourceManager.GetString("ItemNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Tolerance.
        /// </summary>
        public static string ItemPickTolerance {
            get {
                return ResourceManager.GetString("ItemPickTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Point.
        /// </summary>
        public static string ItemReorderPoint {
            get {
                return ResourceManager.GetString("ItemReorderPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Quantity.
        /// </summary>
        public static string ItemReorderQuantity {
            get {
                return ResourceManager.GetString("ItemReorderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for Pick.
        /// </summary>
        public static string ItemReservedForPick {
            get {
                return ResourceManager.GetString("ItemReservedForPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved to Store.
        /// </summary>
        public static string ItemReservedToStore {
            get {
                return ResourceManager.GetString("ItemReservedToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string ItemStock {
            get {
                return ResourceManager.GetString("ItemStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Tolerance.
        /// </summary>
        public static string ItemStoreTolerance {
            get {
                return ResourceManager.GetString("ItemStoreTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ItemWidth {
            get {
                return ResourceManager.GetString("ItemWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string ItemWithdrawArea {
            get {
                return ResourceManager.GetString("ItemWithdrawArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bay.
        /// </summary>
        public static string ItemWithdrawBay {
            get {
                return ResourceManager.GetString("ItemWithdrawBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item.
        /// </summary>
        public static string ItemWithdrawItem {
            get {
                return ResourceManager.GetString("ItemWithdrawItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string ItemWithdrawLot {
            get {
                return ResourceManager.GetString("ItemWithdrawLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ItemWithdrawQuantity {
            get {
                return ResourceManager.GetString("ItemWithdrawQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string ItemWithdrawRegistrationNumber {
            get {
                return ResourceManager.GetString("ItemWithdrawRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub1.
        /// </summary>
        public static string ItemWithdrawSub1 {
            get {
                return ResourceManager.GetString("ItemWithdrawSub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub2.
        /// </summary>
        public static string ItemWithdrawSub2 {
            get {
                return ResourceManager.GetString("ItemWithdrawSub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit.
        /// </summary>
        public static string LoadingUnit {
            get {
                return ResourceManager.GetString("LoadingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Pairing.
        /// </summary>
        public static string LoadingUnitCellPairing {
            get {
                return ResourceManager.GetString("LoadingUnitCellPairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LoadingUnitCode {
            get {
                return ResourceManager.GetString("LoadingUnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Code.
        /// </summary>
        public static string LoadingUnitCode_extended {
            get {
                return ResourceManager.GetString("LoadingUnitCode_extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string LoadingUnitCreationDate {
            get {
                return ResourceManager.GetString("LoadingUnitCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Cell.
        /// </summary>
        public static string LoadingUnitCurrentCell {
            get {
                return ResourceManager.GetString("LoadingUnitCurrentCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling Parameters Correction.
        /// </summary>
        public static string LoadingUnitHandlingParametersCorrection {
            get {
                return ResourceManager.GetString("LoadingUnitHandlingParametersCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string LoadingUnitHeight {
            get {
                return ResourceManager.GetString("LoadingUnitHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Cycle Count.
        /// </summary>
        public static string LoadingUnitInCycleCount {
            get {
                return ResourceManager.GetString("LoadingUnitInCycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Date.
        /// </summary>
        public static string LoadingUnitInventoryDate {
            get {
                return ResourceManager.GetString("LoadingUnitInventoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Handling Date.
        /// </summary>
        public static string LoadingUnitLastHandlingDate {
            get {
                return ResourceManager.GetString("LoadingUnitLastHandlingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Pick Date.
        /// </summary>
        public static string LoadingUnitLastPickDate {
            get {
                return ResourceManager.GetString("LoadingUnitLastPickDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Store Date.
        /// </summary>
        public static string LoadingUnitLastStoreDate {
            get {
                return ResourceManager.GetString("LoadingUnitLastStoreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LoadingUnitLength {
            get {
                return ResourceManager.GetString("LoadingUnitLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string LoadingUnitNotes {
            get {
                return ResourceManager.GetString("LoadingUnitNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cycle Count.
        /// </summary>
        public static string LoadingUnitOtherCycleCount {
            get {
                return ResourceManager.GetString("LoadingUnitOtherCycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Cycle Count.
        /// </summary>
        public static string LoadingUnitOutCycleCount {
            get {
                return ResourceManager.GetString("LoadingUnitOutCycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        public static string LoadingUnitReferenceType {
            get {
                return ResourceManager.GetString("LoadingUnitReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Status.
        /// </summary>
        public static string LoadingUnitStatus {
            get {
                return ResourceManager.GetString("LoadingUnitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Type.
        /// </summary>
        public static string LoadingUnitType {
            get {
                return ResourceManager.GetString("LoadingUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Type Description.
        /// </summary>
        public static string LoadingUnitTypeDescription {
            get {
                return ResourceManager.GetString("LoadingUnitTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string LoadingUnitWeight {
            get {
                return ResourceManager.GetString("LoadingUnitWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string LoadingUnitWidth {
            get {
                return ResourceManager.GetString("LoadingUnitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Weight.
        /// </summary>
        public static string MachineActualWeight {
            get {
                return ResourceManager.GetString("MachineActualWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aisle.
        /// </summary>
        public static string MachineAisle {
            get {
                return ResourceManager.GetString("MachineAisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string MachineArea {
            get {
                return ResourceManager.GetString("MachineArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Time.
        /// </summary>
        public static string MachineAutomaticTime {
            get {
                return ResourceManager.GetString("MachineAutomaticTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Date.
        /// </summary>
        public static string MachineBuildDate {
            get {
                return ResourceManager.GetString("MachineBuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cradles Count.
        /// </summary>
        public static string MachineCradlesCount {
            get {
                return ResourceManager.GetString("MachineCradlesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address.
        /// </summary>
        public static string MachineCustomerAddress {
            get {
                return ResourceManager.GetString("MachineCustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer City.
        /// </summary>
        public static string MachineCustomerCity {
            get {
                return ResourceManager.GetString("MachineCustomerCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code.
        /// </summary>
        public static string MachineCustomerCode {
            get {
                return ResourceManager.GetString("MachineCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Country.
        /// </summary>
        public static string MachineCustomerCountry {
            get {
                return ResourceManager.GetString("MachineCustomerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string MachineCustomerName {
            get {
                return ResourceManager.GetString("MachineCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Time.
        /// </summary>
        public static string MachineErrorTime {
            get {
                return ResourceManager.GetString("MachineErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string MachineImage {
            get {
                return ResourceManager.GetString("MachineImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Loading Units Count.
        /// </summary>
        public static string MachineInputLoadingUnitsCount {
            get {
                return ResourceManager.GetString("MachineInputLoadingUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Date.
        /// </summary>
        public static string MachineInstallationDate {
            get {
                return ResourceManager.GetString("MachineInstallationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Power On.
        /// </summary>
        public static string MachineLastPowerOn {
            get {
                return ResourceManager.GetString("MachineLastPowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Service Date.
        /// </summary>
        public static string MachineLastServiceDate {
            get {
                return ResourceManager.GetString("MachineLastServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string MachineLatitude {
            get {
                return ResourceManager.GetString("MachineLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Units Per Cradle.
        /// </summary>
        public static string MachineLoadingUnitsPerCradle {
            get {
                return ResourceManager.GetString("MachineLoadingUnitsPerCradle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string MachineLongitude {
            get {
                return ResourceManager.GetString("MachineLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Time.
        /// </summary>
        public static string MachineManualTime {
            get {
                return ResourceManager.GetString("MachineManualTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Time.
        /// </summary>
        public static string MachineMissionTime {
            get {
                return ResourceManager.GetString("MachineMissionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string MachineModel {
            get {
                return ResourceManager.GetString("MachineModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved Loading Units Count.
        /// </summary>
        public static string MachineMovedLoadingUnitsCount {
            get {
                return ResourceManager.GetString("MachineMovedLoadingUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Service Date.
        /// </summary>
        public static string MachineNextServiceDate {
            get {
                return ResourceManager.GetString("MachineNextServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string MachineNickname {
            get {
                return ResourceManager.GetString("MachineNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputLoadingUnitsCount.
        /// </summary>
        public static string MachineOutputLoadingUnitsCount {
            get {
                return ResourceManager.GetString("MachineOutputLoadingUnitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On Time.
        /// </summary>
        public static string MachinePowerOnTime {
            get {
                return ResourceManager.GetString("MachinePowerOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string MachineRegistrationNumber {
            get {
                return ResourceManager.GetString("MachineRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Date.
        /// </summary>
        public static string MachineTestDate {
            get {
                return ResourceManager.GetString("MachineTestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Max Weight.
        /// </summary>
        public static string MachineTotalMaxWeight {
            get {
                return ResourceManager.GetString("MachineTotalMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MachineTypeDescription {
            get {
                return ResourceManager.GetString("MachineTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Status.
        /// </summary>
        public static string MaterialStatus {
            get {
                return ResourceManager.GetString("MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Unit.
        /// </summary>
        public static string MeasureUnitDescription {
            get {
                return ResourceManager.GetString("MeasureUnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        public static string PackageType {
            get {
                return ResourceManager.GetString("PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
    }
}
