//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DesktopApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesktopApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.Common.Resources.DesktopApp", typeof(DesktopApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMS – Ferretto Group.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Prism module catalog ....
        /// </summary>
        public static string ConfiguringPrismModuleCatalog {
            get {
                return ResourceManager.GetString("ConfiguringPrismModuleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Entity Framework ... done..
        /// </summary>
        public static string DoneInitializingEntityFramework {
            get {
                return ResourceManager.GetString("DoneInitializingEntityFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Compartment module ....
        /// </summary>
        public static string InitializingCompartmentModule {
            get {
                return ResourceManager.GetString("InitializingCompartmentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Entity Framework ....
        /// </summary>
        public static string InitializingEntityFramework {
            get {
                return ResourceManager.GetString("InitializingEntityFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Layout module ....
        /// </summary>
        public static string InitializingLayoutModule {
            get {
                return ResourceManager.GetString("InitializingLayoutModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing main window ....
        /// </summary>
        public static string InitializingMainWindow {
            get {
                return ResourceManager.GetString("InitializingMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Master Data module ....
        /// </summary>
        public static string InitializingMasterDataModule {
            get {
                return ResourceManager.GetString("InitializingMasterDataModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Prism module catalog ....
        /// </summary>
        public static string LoadingPrismModuleCatalog {
            get {
                return ResourceManager.GetString("LoadingPrismModuleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening main window ....
        /// </summary>
        public static string OpeningMainWindow {
            get {
                return ResourceManager.GetString("OpeningMainWindow", resourceCulture);
            }
        }
    }
}
