//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemLists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemLists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.Common.Resources.ItemLists", typeof(ItemLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Order Information.
        /// </summary>
        public static string CustomerOrderInformation {
            get {
                return ResourceManager.GetString("CustomerOrderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Details.
        /// </summary>
        public static string ExecutionDetails {
            get {
                return ResourceManager.GetString("ExecutionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List deleted successfully.
        /// </summary>
        public static string ItemListDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ItemListDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute List.
        /// </summary>
        public static string ItemListExecute {
            get {
                return ResourceManager.GetString("ItemListExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute List Options.
        /// </summary>
        public static string ItemListExecuteOptions {
            get {
                return ResourceManager.GetString("ItemListExecuteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Information.
        /// </summary>
        public static string ItemListInformation {
            get {
                return ResourceManager.GetString("ItemListInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List request accepted.
        /// </summary>
        public static string ItemListRequestAccepted {
            get {
                return ResourceManager.GetString("ItemListRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Row List.
        /// </summary>
        public static string ItemListRowAdd {
            get {
                return ResourceManager.GetString("ItemListRowAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item List Row deleted successfully.
        /// </summary>
        public static string ItemListRowDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ItemListRowDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Row List.
        /// </summary>
        public static string ItemListRowExecute {
            get {
                return ResourceManager.GetString("ItemListRowExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute List Row Options.
        /// </summary>
        public static string ItemListRowExecuteOptions {
            get {
                return ResourceManager.GetString("ItemListRowExecuteOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Rows Information.
        /// </summary>
        public static string ItemListRowInformation {
            get {
                return ResourceManager.GetString("ItemListRowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Row request accepted.
        /// </summary>
        public static string ItemListRowRequestAccepted {
            get {
                return ResourceManager.GetString("ItemListRowRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Rows.
        /// </summary>
        public static string ItemListRows {
            get {
                return ResourceManager.GetString("ItemListRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item list row saved sucessfully.
        /// </summary>
        public static string ItemListRowSavedSuccessfully {
            get {
                return ResourceManager.GetString("ItemListRowSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details Row List.
        /// </summary>
        public static string ItemListRowShowDetails {
            get {
                return ResourceManager.GetString("ItemListRowShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item list saved sucessfully.
        /// </summary>
        public static string ItemListSavedSuccessfully {
            get {
                return ResourceManager.GetString("ItemListSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list has no rows..
        /// </summary>
        public static string ItemListWithNoRows {
            get {
                return ResourceManager.GetString("ItemListWithNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute List.
        /// </summary>
        public static string RunItemList {
            get {
                return ResourceManager.GetString("RunItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Row List.
        /// </summary>
        public static string RunItemListRow {
            get {
                return ResourceManager.GetString("RunItemListRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Unit Information.
        /// </summary>
        public static string ShipmentUnitInformation {
            get {
                return ResourceManager.GetString("ShipmentUnitInformation", resourceCulture);
            }
        }
    }
}
