//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Navigation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Navigation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.Common.Resources.Navigation", typeof(Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC Classes.
        /// </summary>
        public static string AbcClasses {
            get {
                return ResourceManager.GetString("AbcClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Lists.
        /// </summary>
        public static string AllLists {
            get {
                return ResourceManager.GetString("AllLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Details.
        /// </summary>
        public static string CellDetails {
            get {
                return ResourceManager.GetString("CellDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string Cells {
            get {
                return ResourceManager.GetString("Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Statuses.
        /// </summary>
        public static string CellStatuses {
            get {
                return ResourceManager.GetString("CellStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Details.
        /// </summary>
        public static string CompartmentDetails {
            get {
                return ResourceManager.GetString("CompartmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartments.
        /// </summary>
        public static string Compartments {
            get {
                return ResourceManager.GetString("Compartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartments Mapping.
        /// </summary>
        public static string CompartmentsMapping {
            get {
                return ResourceManager.GetString("CompartmentsMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Statuses.
        /// </summary>
        public static string CompartmentStatuses {
            get {
                return ResourceManager.GetString("CompartmentStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartment Types.
        /// </summary>
        public static string CompartmentTypes {
            get {
                return ResourceManager.GetString("CompartmentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export.
        /// </summary>
        public static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        public static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Withdraw.
        /// </summary>
        public static string ItemWithdraw {
            get {
                return ResourceManager.GetString("ItemWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Row Statuses.
        /// </summary>
        public static string ListRowStatuses {
            get {
                return ResourceManager.GetString("ListRowStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Statuses.
        /// </summary>
        public static string ListStatuses {
            get {
                return ResourceManager.GetString("ListStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Types.
        /// </summary>
        public static string ListTypes {
            get {
                return ResourceManager.GetString("ListTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Edit.
        /// </summary>
        public static string LoadingUnitEdit {
            get {
                return ResourceManager.GetString("LoadingUnitEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Details.
        /// </summary>
        public static string LoadingUnitDetails {
            get {
                return ResourceManager.GetString("LoadingUnitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Units.
        /// </summary>
        public static string LoadingUnits {
            get {
                return ResourceManager.GetString("LoadingUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Unit Statuses.
        /// </summary>
        public static string LoadingUnitStatuses {
            get {
                return ResourceManager.GetString("LoadingUnitStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status.
        /// </summary>
        public static string Machine_Status {
            get {
                return ResourceManager.GetString("Machine_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string Machines {
            get {
                return ResourceManager.GetString("Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Types.
        /// </summary>
        public static string MachineTypes {
            get {
                return ResourceManager.GetString("MachineTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string MasterData {
            get {
                return ResourceManager.GetString("MasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Statuses.
        /// </summary>
        public static string MaterialStatuses {
            get {
                return ResourceManager.GetString("MaterialStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Types.
        /// </summary>
        public static string PackageTypes {
            get {
                return ResourceManager.GetString("PackageTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understock Items.
        /// </summary>
        public static string UnderStockItems {
            get {
                return ResourceManager.GetString("UnderStockItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units of Measurement.
        /// </summary>
        public static string UnitsOfMeasurement {
            get {
                return ResourceManager.GetString("UnitsOfMeasurement", resourceCulture);
            }
        }
    }
}
