//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ferretto.VW.MAS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ferretto.VW.MAS.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request..
        /// </summary>
        public static string BadRequestTitle {
            get {
                return ResourceManager.GetString("BadRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry error.
        /// </summary>
        public static string DataEntryError {
            get {
                return ResourceManager.GetString("DataEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Zero not possible with full elevator.
        /// </summary>
        public static string FindZeroFullElevator {
            get {
                return ResourceManager.GetString("FindZeroFullElevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Zero not possible: Invalid Bay Zero sensor.
        /// </summary>
        public static string FindZeroInvalidBayZero {
            get {
                return ResourceManager.GetString("FindZeroInvalidBayZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homing not possible with open shutter.
        /// </summary>
        public static string HomingShutterOpen {
            get {
                return ResourceManager.GetString("HomingShutterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        public static string InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intrusion detected by height reading barrier.
        /// </summary>
        public static string IntrusionDetected {
            get {
                return ResourceManager.GetString("IntrusionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid presence sensors: Zero sensor: {0}, completely on board: {1}.
        /// </summary>
        public static string InvalidPresenceSensors {
            get {
                return ResourceManager.GetString("InvalidPresenceSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance status expired.
        /// </summary>
        public static string MaintenanceStateExpired {
            get {
                return ResourceManager.GetString("MaintenanceStateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance status expiring.
        /// </summary>
        public static string MaintenanceStateExpiring {
            get {
                return ResourceManager.GetString("MaintenanceStateExpiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entity with the specified id &apos;{0}&apos; exists..
        /// </summary>
        public static string NoEntityWithTheSpecifiedIdExists {
            get {
                return ResourceManager.GetString("NoEntityWithTheSpecifiedIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found..
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is initializing..
        /// </summary>
        public static string ServiceIsInitializing {
            get {
                return ResourceManager.GetString("ServiceIsInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service startup sequence completed..
        /// </summary>
        public static string ServiceStartupSequenceCompleted {
            get {
                return ResourceManager.GetString("ServiceStartupSequenceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unprocessable Entity..
        /// </summary>
        public static string UnprocessableEntityTitle {
            get {
                return ResourceManager.GetString("UnprocessableEntityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        public static string ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
